Guidelime.registerGuide(
[[
[GA Horde]
[N1-6Undead]
[NX6-12Undead]
[D This guide was written by TUGs and is totally free, but if you want to support my work use: https://www.youtube.com/user/HydroxXTV]
This guide was written by TUGs and is totally free, but if you want to support my work use: https://www.youtube.com/user/HydroxXTV
I am leaving out EVERY Elite quest and most dungeons in this guide. especially on release YOU SHOULD NOT!!! You'll easily find groups for elite quests and dungeons. Do them as often as you can and at least once for their quests!
Accept: [QA363]
Kill as many mobs on your way down the road as you can
TurnIn: [QT363]
Accept: [QA364]
Do: [QC364]
TurnIn: [QT364]
Accept: [QA3098][A Mage]
TurnIn: [QT3098][A Mage]
Accept: [QA3095][A Warrior]
Accept: [QA3901]
Accept: [QA376]
TurnIn: [QT3095][A Warrior]
Grind in Deathknell till level [XP3 3]
Do [QC3901- ][QC376 Rattling the Rattlecages AND The Damned]
TurnIn: [QT3901]
TurnIn: [QT376]
Accept: [QA6395]
Accept: [QA380]
Accept: [QA3902]
Find as many Scavanged Goods in Deathknell whilst going to the next marker
Kill Samuel Fipps at[G 36.7,61.8 Tirisfal Glades] for Marla's Last Wish
Do: [QC3902]
Do: [QC380]
Die and resurrect
Do: [QC6395]
TurnIn: [QT3902]
TurnIn: [QT6395]
TurnIn: [QT380]
Accept: [QA381]
Do: [QC381]
TurnIn: [QT381]
Accept: [QA382]
Do: [QC382]
TurnIn: [QT382]
Accept: [QA383]
Accept: [QA8]
Accept: [QA365]
Do: [QC365]
Make sure you're [XP6]. If you see Gordo on the way, accept his quest. If you don't, dont worry you'll get a second chance soon.
Accept: [QA404]
TurnIn: [QT365]
Accept: [QA407]
Accept: [QA367]
TurnIn: [QT383]
Accept: [QA427]
Accept: [QA398]
Accept: [QA358]
TurnIn: [QT8]
Set your [H] to Tirisfal Glades at [G61.6, 52.0Tirisfal Glades]
TurnIn: [QT407]
TurnIn: [QT5651]
]], "TUGs The Ultimate (Leveling) Guides")