{pkgs, ...}: {
  environment.systemPackages = with pkgs; [
    darwin.apple_sdk.frameworks.AGL
    darwin.apple_sdk.frameworks.AVFoundation
    darwin.apple_sdk.frameworks.AVKit
    darwin.apple_sdk.frameworks.Accelerate
    darwin.apple_sdk.frameworks.Accounts
    darwin.apple_sdk.frameworks.AddressBook
    darwin.apple_sdk.frameworks.AppKit
    darwin.apple_sdk.frameworks.AppleScriptKit
    darwin.apple_sdk.frameworks.AppleScriptObjC
    darwin.apple_sdk.frameworks.ApplicationServices
    darwin.apple_sdk.frameworks.AudioToolbox
    darwin.apple_sdk.frameworks.AudioUnit
    darwin.apple_sdk.frameworks.AudioVideoBridging
    darwin.apple_sdk.frameworks.Automator
    darwin.apple_sdk.frameworks.CFNetwork
    darwin.apple_sdk.frameworks.CalendarStore
    darwin.apple_sdk.frameworks.Carbon
    darwin.apple_sdk.frameworks.Cocoa
    darwin.apple_sdk.frameworks.Collaboration
    darwin.apple_sdk.frameworks.CoreAudio
    darwin.apple_sdk.frameworks.CoreAudioKit
    darwin.apple_sdk.frameworks.CoreBluetooth
    darwin.apple_sdk.frameworks.CoreData
    darwin.apple_sdk.frameworks.CoreFoundation
    darwin.apple_sdk.frameworks.CoreGraphics
    darwin.apple_sdk.frameworks.CoreImage
    darwin.apple_sdk.frameworks.CoreLocation
    darwin.apple_sdk.frameworks.CoreMIDI
    darwin.apple_sdk.frameworks.CoreMIDIServer
    darwin.apple_sdk.frameworks.CoreMedia
    darwin.apple_sdk.frameworks.CoreMediaIO
    darwin.apple_sdk.frameworks.CoreServices
    darwin.apple_sdk.frameworks.CoreText
    darwin.apple_sdk.frameworks.CoreVideo
    darwin.apple_sdk.frameworks.CoreWLAN
    darwin.apple_sdk.frameworks.DVDPlayback
    darwin.apple_sdk.frameworks.DirectoryService
    darwin.apple_sdk.frameworks.DiscRecording
    darwin.apple_sdk.frameworks.DiscRecordingUI
    darwin.apple_sdk.frameworks.DiskArbitration
    darwin.apple_sdk.frameworks.EventKit
    darwin.apple_sdk.frameworks.ExceptionHandling
    darwin.apple_sdk.frameworks.FWAUserLib
    darwin.apple_sdk.frameworks.ForceFeedback
    darwin.apple_sdk.frameworks.Foundation
    darwin.apple_sdk.frameworks.GLKit
    darwin.apple_sdk.frameworks.GLUT
    darwin.apple_sdk.frameworks.GSS
    darwin.apple_sdk.frameworks.GameController
    darwin.apple_sdk.frameworks.GameKit
    darwin.apple_sdk.frameworks.GameplayKit
    darwin.apple_sdk.frameworks.Hypervisor
    darwin.apple_sdk.frameworks.ICADevices
    darwin.apple_sdk.frameworks.IMServicePlugIn
    darwin.apple_sdk.frameworks.IOBluetooth
    darwin.apple_sdk.frameworks.IOBluetoothUI
    darwin.apple_sdk.frameworks.IOKit
    darwin.apple_sdk.frameworks.IOSurface
    darwin.apple_sdk.frameworks.ImageCaptureCore
    darwin.apple_sdk.frameworks.ImageIO
    darwin.apple_sdk.frameworks.InputMethodKit
    darwin.apple_sdk.frameworks.InstallerPlugins
    darwin.apple_sdk.frameworks.InstantMessage
    darwin.apple_sdk.frameworks.Kerberos
    darwin.apple_sdk.frameworks.Kernel
    darwin.apple_sdk.frameworks.LDAP
    darwin.apple_sdk.frameworks.LatentSemanticMapping
    darwin.apple_sdk.frameworks.LocalAuthentication
    darwin.apple_sdk.frameworks.MapKit
    darwin.apple_sdk.frameworks.MediaAccessibility
    darwin.apple_sdk.frameworks.MediaPlayer
    darwin.apple_sdk.frameworks.MediaToolbox
    darwin.apple_sdk.frameworks.Metal
    darwin.apple_sdk.frameworks.MetalKit
    darwin.apple_sdk.frameworks.ModelIO
    darwin.apple_sdk.frameworks.NetFS
    darwin.apple_sdk.frameworks.OSAKit
    darwin.apple_sdk.frameworks.OpenAL
    darwin.apple_sdk.frameworks.OpenCL
    darwin.apple_sdk.frameworks.OpenDirectory
    darwin.apple_sdk.frameworks.OpenGL
    darwin.apple_sdk.frameworks.PCSC
    darwin.apple_sdk.frameworks.PreferencePanes
    darwin.apple_sdk.frameworks.QTKit
    darwin.apple_sdk.frameworks.Quartz
    darwin.apple_sdk.frameworks.QuartzCore
    darwin.apple_sdk.frameworks.QuickLook
    darwin.apple_sdk.frameworks.SceneKit
    darwin.apple_sdk.frameworks.ScreenSaver
    darwin.apple_sdk.frameworks.Security
    darwin.apple_sdk.frameworks.SecurityFoundation
    darwin.apple_sdk.frameworks.SecurityInterface
    darwin.apple_sdk.frameworks.ServiceManagement
    darwin.apple_sdk.frameworks.Social
    darwin.apple_sdk.frameworks.SpriteKit
    darwin.apple_sdk.frameworks.StoreKit
    darwin.apple_sdk.frameworks.SyncServices
    darwin.apple_sdk.frameworks.System
    darwin.apple_sdk.frameworks.SystemConfiguration
    darwin.apple_sdk.frameworks.TWAIN
    darwin.apple_sdk.frameworks.Tcl
    darwin.apple_sdk.frameworks.VideoDecodeAcceleration
    darwin.apple_sdk.frameworks.VideoToolbox
    darwin.apple_sdk.frameworks.WebKit
    darwin.apple_sdk.frameworks.vmnet
  ];
}
