@startuml
nwdiag {
  network firewall {
    address = "192.168.8.21/24"
    vmfirewall [address = "vm-firewall-in, vm-firewall-out"]
  }

  network {
    host [address = "br0"]
    vmi2pd [address = "vm-i2pd-in, vm-i2pd-out"]
    vmtor [address = "vm-tor-in, vm-tor-out"]
  }

  host -- vmfirewall
  vmi2pd -- vmfirewall
  vmtor -- vmfirewall
}
@enduml