[package]
name = "cl"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "A simple terminal clear command written in Rust"

[dependencies]

[[bin]]
name = "cl"
path = "src/main.rs"
