import type { BdToolSpec, ParamSpec, ToolTestCase } from "./bdTypes";
import { buildBdCommandFromSpec } from "./buildBdCommand";

const issueIds = (
    description = "Issue IDs to operate on.",
    required = true,
): ParamSpec => ({
    name: "issueIds",
    type: "string[]",
    description,
    required,
    position: "leading",
    joinWith: " ",
    quote: false,
});

const filterParams: ParamSpec[] = [
    {
        name: "query",
        type: "string",
        description: "Query string for filtering issues.",
        quote: true,
    },
    {
        name: "type",
        type: "string",
        description: "Filter by issue type.",
    },
    {
        name: "status",
        type: "string",
        description: "Filter by issue status.",
    },
    {
        name: "assignee",
        type: "string",
        description: "Filter by assignee username.",
    },
    {
        name: "labels",
        type: "string[]",
        description: "Filter by labels.",
        joinWith: ",",
    },
];

const sortParams: ParamSpec[] = [
    {
        name: "sort",
        type: "string",
        description: "Field to sort by.",
    },
    {
        name: "reverse",
        type: "boolean",
        description: "Reverse the sort order.",
        flag: "reverse",
    },
    {
        name: "limit",
        type: "number",
        description: "Maximum number of issues to return.",
        flag: "limit",
    },
];

const passthrough = (
    name: string,
    subcommand: string,
    description: string,
    commandParam = "command",
): BdToolSpec => ({
    name,
    description,
    subcommand,
    outputKey: "result",
    params: [
        {
            name: commandParam,
            type: "string",
            description: `Subcommand arguments for ${subcommand}.`,
            required: true,
            position: "trailing",
            quote: false,
        },
    ],
});

export const BD_TOOL_SPECS: BdToolSpec[] = [
    {
        name: "bd_version",
        description: "Get the current version of the Beads CLI (bd).",
        subcommand: "--version",
        params: [],
        outputKey: "version",
        includeGlobalFlags: false,
    },
    {
        name: "bd_assign",
        description: "Assign one or more issues to an actor.",
        subcommand: "assign",
        outputKey: "result",
        params: [
            issueIds(),
            {
                name: "actor",
                type: "string",
                description: "Actor to assign issues to.",
                required: true,
                flag: "actor",
                quote: false,
            },
        ],
    },
    {
        name: "bd_children",
        description: "List direct child issues of a parent issue.",
        subcommand: "children",
        outputKey: "result",
        params: [
            {
                name: "issueId",
                type: "string",
                description: "Parent issue ID.",
                required: true,
                position: "trailing",
                quote: false,
            },
        ],
    },
    {
        name: "bd_close",
        description: "Close one or more issues.",
        subcommand: "close",
        outputKey: "result",
        params: [issueIds()],
    },
    {
        name: "bd_comment",
        description: "Add a comment to an issue.",
        subcommand: "comment",
        outputKey: "result",
        params: [
            {
                name: "issueId",
                type: "string",
                description: "Issue ID.",
                required: true,
                position: "leading",
                quote: false,
            },
            {
                name: "actor",
                type: "string",
                description: "Comment actor.",
                flag: "actor",
                quote: false,
            },
            {
                name: "body",
                type: "string",
                description: "Comment body text.",
                flag: "body",
                quote: true,
            },
            {
                name: "file",
                type: "string",
                description: "Path to comment body file.",
                flag: "file",
                quote: true,
            },
        ],
    },
    {
        name: "bd_comments",
        description: "View comments on an issue.",
        subcommand: "comments",
        outputKey: "result",
        params: [
            {
                name: "issueId",
                type: "string",
                description: "Issue ID.",
                required: true,
                position: "trailing",
                quote: false,
            },
            {
                name: "limit",
                type: "number",
                description: "Maximum number of comments.",
                flag: "limit",
            },
        ],
    },
    {
        name: "bd_create",
        description:
            "Create a new issue. Supports title, description, markdown, or JSON.",
        subcommand: "create",
        outputKey: "creationResult",
        params: [
            {
                name: "title",
                type: "string",
                description: "Issue title.",
                flag: "title",
                quote: true,
            },
            {
                name: "type",
                type: "string",
                description: "Issue type.",
                flag: "type",
                quote: false,
            },
            {
                name: "description",
                type: "string",
                description: "Issue description.",
                flag: "description",
                quote: true,
            },
            {
                name: "parent",
                type: "string",
                description: "Parent issue ID.",
                flag: "parent",
                quote: false,
            },
            {
                name: "body",
                type: "string",
                description: "Path to body file.",
                flag: "body",
                quote: true,
            },
            {
                name: "file",
                type: "string",
                description: "Path to content file.",
                flag: "file",
                quote: true,
            },
            {
                name: "markdown",
                type: "string",
                description: "Markdown body content.",
                flag: "markdown",
                quote: true,
                escapeQuotes: true,
            },
            {
                name: "json",
                type: "string",
                description: "JSON creation payload.",
                flag: "json",
                quote: true,
                escapeQuotes: true,
            },
            {
                name: "actor",
                type: "string",
                description: "Creating actor.",
                flag: "actor",
                quote: false,
            },
            {
                name: "batch",
                type: "boolean",
                description: "Enable batch creation mode.",
                flag: "batch",
            },
        ],
        buildCommand(args) {
            const spec = BD_TOOL_SPECS.find((entry) => entry.name === "bd_create")!;
            const base = buildBdCommandFromSpec(
                { ...spec, buildCommand: undefined },
                args,
            );
            if (base !== "create") {
                return base;
            }
            return "create --title 'New Issue Creation'";
        },
    },
    {
        name: "bd_create_form",
        description: "Create a new issue using an interactive form.",
        subcommand: "create-form",
        outputKey: "result",
        params: [],
    },
    {
        name: "bd_delete",
        description: "Delete one or more issues.",
        subcommand: "delete",
        outputKey: "result",
        params: [issueIds()],
    },
    {
        name: "bd_edit",
        description: "Edit an issue field or body.",
        subcommand: "edit",
        outputKey: "result",
        params: [
            {
                name: "issueId",
                type: "string",
                description: "Issue ID.",
                required: true,
                position: "leading",
                quote: false,
            },
            {
                name: "field",
                type: "string",
                description: "Field name to edit.",
                flag: "field",
            },
            {
                name: "value",
                type: "string",
                description: "New field value.",
                flag: "value",
                quote: true,
            },
            {
                name: "body",
                type: "string",
                description: "Markdown body file path.",
                flag: "body",
                quote: true,
            },
            {
                name: "file",
                type: "string",
                description: "File path for edit content.",
                flag: "file",
                quote: true,
            },
            {
                name: "directory",
                type: "string",
                description: "Directory to run edit in (-C).",
                shortFlag: "C",
            },
        ],
        includeGlobalFlags: false,
    },
    {
        name: "bd_gate",
        description: "Manage asynchronous coordination gates.",
        subcommand: "gate",
        outputKey: "result",
        params: [
            issueIds(),
            {
                name: "condition",
                type: "string",
                description: "Gate condition.",
                required: true,
                flag: "condition",
                quote: true,
            },
            {
                name: "wait",
                type: "string",
                description: "Wait duration.",
                flag: "wait",
            },
            {
                name: "action",
                type: "string",
                description: "Gate action.",
                flag: "action",
            },
        ],
    },
    {
        name: "bd_label",
        description: "Add or remove labels on issues.",
        subcommand: "label",
        outputKey: "result",
        params: [
            issueIds(),
            {
                name: "add",
                type: "string[]",
                description: "Labels to add.",
                flag: "add",
                joinWith: " ",
            },
            {
                name: "remove",
                type: "string[]",
                description: "Labels to remove.",
                flag: "remove",
                joinWith: " ",
            },
        ],
    },
    {
        name: "bd_link",
        description: "Link two issues together.",
        subcommand: "link",
        outputKey: "result",
        params: [
            {
                name: "issueId1",
                type: "string",
                description: "First issue ID.",
                required: true,
                position: "leading",
                quote: false,
            },
            {
                name: "issueId2",
                type: "string",
                description: "Second issue ID.",
                required: true,
                position: "leading",
                quote: false,
            },
            {
                name: "relation",
                type: "string",
                description: "Link relation type.",
                flag: "relation",
            },
        ],
    },
    {
        name: "bd_list",
        description: "List issues matching filters.",
        subcommand: "list",
        outputKey: "issues",
        params: [
            ...filterParams,
            ...sortParams,
            {
                name: "format",
                type: "string",
                description: "Output format.",
                flag: "format",
            },
        ],
    },
    {
        name: "bd_merge_slot",
        description: "Manage merge-slot gates.",
        subcommand: "merge-slot",
        outputKey: "result",
        params: [
            issueIds(),
            {
                name: "condition",
                type: "string",
                description: "Merge slot condition.",
                required: true,
                flag: "condition",
                quote: true,
            },
            {
                name: "wait",
                type: "string",
                description: "Wait duration.",
                flag: "wait",
            },
        ],
    },
    {
        name: "bd_note",
        description: "Append a note to an issue.",
        subcommand: "note",
        outputKey: "result",
        params: [
            {
                name: "issueId",
                type: "string",
                description: "Issue ID.",
                required: true,
                position: "leading",
                quote: false,
            },
            {
                name: "noteText",
                type: "string",
                description: "Note text.",
                required: true,
                position: "trailing",
                quote: true,
            },
        ],
    },
    {
        name: "bd_priority",
        description: "Set issue priority.",
        subcommand: "priority",
        outputKey: "result",
        params: [
            issueIds(),
            {
                name: "priority",
                type: "string",
                description: "Priority level.",
                required: true,
                flag: "priority",
                quote: false,
            },
        ],
    },
    {
        name: "bd_promote",
        description: "Promote a wisp issue to a permanent bead.",
        subcommand: "promote",
        outputKey: "result",
        params: [
            {
                name: "issueId",
                type: "string",
                description: "Issue ID.",
                required: true,
                position: "trailing",
                quote: false,
            },
        ],
    },
    {
        name: "bd_q",
        description: "Quick capture: create issue and output only its ID.",
        subcommand: "q",
        outputKey: "result",
        params: [],
    },
    {
        name: "bd_query",
        description: "Query issues using structured query language.",
        subcommand: "query",
        outputKey: "result",
        params: [
            {
                name: "queryString",
                type: "string",
                description: "Query string.",
                required: true,
                position: "leading",
                quote: true,
            },
            ...filterParams.filter((param) => param.name !== "query"),
            ...sortParams,
        ],
    },
    {
        name: "bd_reopen",
        description: "Reopen closed issues.",
        subcommand: "reopen",
        outputKey: "result",
        params: [issueIds()],
    },
    {
        name: "bd_search",
        description: "Search issues by text query.",
        subcommand: "search",
        outputKey: "result",
        params: [
            {
                name: "textQuery",
                type: "string",
                description: "Text search query.",
                required: true,
                position: "leading",
                quote: true,
            },
            ...filterParams.filter((param) => param.name !== "query"),
            {
                name: "limit",
                type: "number",
                description: "Maximum number of results.",
                flag: "limit",
            },
        ],
    },
    {
        name: "bd_set_state",
        description: "Set operational state for issues.",
        subcommand: "set-state",
        outputKey: "result",
        params: [
            issueIds(),
            {
                name: "state",
                type: "string",
                description: "Target state name.",
                required: true,
                flag: "state",
            },
            {
                name: "actor",
                type: "string",
                description: "Actor performing the transition.",
                flag: "actor",
                quote: false,
            },
            {
                name: "comment",
                type: "string",
                description: "Transition comment.",
                flag: "comment",
                quote: true,
            },
        ],
    },
    {
        name: "bd_show",
        description: "Show detailed information for a specific issue.",
        subcommand: "show",
        outputKey: "issueDetails",
        params: [
            {
                name: "issueId",
                type: "string",
                description: "Issue ID.",
                required: true,
                position: "leading",
                quote: true,
            },
            {
                name: "format",
                type: "string",
                description: "Output format.",
                flag: "format",
            },
            {
                name: "commentLimit",
                type: "number",
                description: "Maximum comments to show.",
                flag: "comment-limit",
            },
            {
                name: "dependencyDepth",
                type: "number",
                description: "Dependency display depth.",
                flag: "dependency-depth",
            },
            {
                name: "history",
                type: "boolean",
                description: "Include issue history.",
                flag: "history",
            },
            {
                name: "noDeps",
                type: "boolean",
                description: "Hide dependencies.",
                flag: "no-deps",
            },
            {
                name: "noComments",
                type: "boolean",
                description: "Hide comments.",
                flag: "no-comments",
            },
        ],
        validate(args) {
            if (!args.issueId) {
                throw new Error("issueId is required to show an issue.");
            }
        },
    },
    {
        name: "bd_state",
        description: "Query state dimension values.",
        subcommand: "state",
        outputKey: "result",
        params: [
            {
                name: "dimension",
                type: "string",
                description: "State dimension name.",
                required: true,
                position: "leading",
                quote: false,
            },
            {
                name: "list",
                type: "boolean",
                description: "List dimension values.",
                flag: "list",
            },
            {
                name: "query",
                type: "string",
                description: "Dimension query.",
                flag: "query",
                quote: true,
            },
        ],
    },
    {
        name: "bd_tag",
        description: "Alias for label: add or remove labels.",
        subcommand: "tag",
        outputKey: "result",
        params: [
            issueIds(),
            {
                name: "add",
                type: "string[]",
                description: "Labels to add.",
                flag: "add",
                joinWith: " ",
            },
            {
                name: "remove",
                type: "string[]",
                description: "Labels to remove.",
                flag: "remove",
                joinWith: " ",
            },
        ],
    },
    {
        name: "bd_todo",
        description: "Manage TODO items associated with issues.",
        subcommand: "todo",
        outputKey: "result",
        params: [
            {
                name: "add",
                type: "string",
                description: "Task description to add.",
                flag: "add",
                quote: true,
            },
            {
                name: "list",
                type: "boolean",
                description: "List todos.",
                flag: "list",
            },
            {
                name: "complete",
                type: "string",
                description: "Task ID to complete.",
                flag: "complete",
            },
        ],
    },
    {
        name: "bd_update",
        description: "Update a specific field on issues.",
        subcommand: "update",
        outputKey: "result",
        params: [
            issueIds(),
            {
                name: "field",
                type: "string",
                description: "Field name.",
                required: true,
                flag: "field",
            },
            {
                name: "value",
                type: "string",
                description: "New field value.",
                required: true,
                flag: "value",
                quote: true,
            },
        ],
    },
    {
        name: "bd_count",
        description: "Count issues matching filters.",
        subcommand: "count",
        outputKey: "result",
        params: [...filterParams],
    },
    {
        name: "bd_diff",
        description: "Show changes between commits or branches.",
        subcommand: "diff",
        outputKey: "result",
        params: [
            {
                name: "base",
                type: "string",
                description: "Base commit.",
                flag: "base",
            },
            {
                name: "head",
                type: "string",
                description: "Head commit.",
                flag: "head",
            },
            {
                name: "path",
                type: "string",
                description: "Path filter.",
                flag: "path",
            },
            {
                name: "type",
                type: "string",
                description: "Diff type filter.",
                flag: "type",
            },
        ],
    },
    {
        name: "bd_find_duplicates",
        description: "Find semantically similar duplicate issues.",
        subcommand: "find-duplicates",
        outputKey: "result",
        params: [
            {
                name: "strategy",
                type: "string",
                description: "Duplicate detection strategy.",
                flag: "strategy",
            },
            {
                name: "threshold",
                type: "number",
                description: "Similarity threshold.",
                flag: "threshold",
            },
            {
                name: "autoMerge",
                type: "boolean",
                description: "Automatically merge duplicates.",
                flag: "auto-merge",
            },
        ],
    },
    {
        name: "bd_history",
        description: "Show version history for an issue.",
        subcommand: "history",
        outputKey: "result",
        params: [
            {
                name: "issueId",
                type: "string",
                description: "Issue ID.",
                required: true,
                position: "trailing",
                quote: false,
            },
        ],
    },
    {
        name: "bd_lint",
        description: "Lint issues for template and format problems.",
        subcommand: "lint",
        outputKey: "result",
        params: [
            {
                name: "fix",
                type: "boolean",
                description: "Attempt to fix lint issues.",
                flag: "fix",
            },
        ],
    },
    {
        name: "bd_stale",
        description: "Show issues not updated recently.",
        subcommand: "stale",
        outputKey: "result",
        params: [
            {
                name: "query",
                type: "string",
                description: "Query filter.",
                flag: "query",
                quote: true,
            },
            {
                name: "days",
                type: "number",
                description: "Stale threshold in days.",
                flag: "days",
            },
            {
                name: "assignee",
                type: "string",
                description: "Assignee filter.",
                flag: "assignee",
            },
        ],
    },
    {
        name: "bd_status",
        description: "Show issue database overview statistics.",
        subcommand: "status",
        outputKey: "result",
        params: [
            {
                name: "format",
                type: "string",
                description: "Output format.",
                flag: "format",
            },
        ],
    },
    {
        name: "bd_statuses",
        description: "List valid issue statuses.",
        subcommand: "statuses",
        outputKey: "result",
        params: [
            {
                name: "list",
                type: "boolean",
                description: "List statuses.",
                flag: "list",
            },
        ],
    },
    {
        name: "bd_types",
        description: "List valid issue types.",
        subcommand: "types",
        outputKey: "result",
        params: [
            {
                name: "list",
                type: "boolean",
                description: "List types.",
                flag: "list",
            },
        ],
    },
    {
        name: "bd_dep_add",
        description: "Add a dependency between two issues.",
        subcommand: "dep add",
        outputKey: "result",
        params: [
            {
                name: "issueId1",
                type: "string",
                description: "Dependent issue ID.",
                required: true,
                position: "leading",
                quote: false,
            },
            {
                name: "issueId2",
                type: "string",
                description: "Dependency issue ID.",
                required: true,
                position: "leading",
                quote: false,
            },
            {
                name: "type",
                type: "string",
                description: "Dependency type.",
                flag: "type",
            },
        ],
    },
    {
        name: "bd_dep_rm",
        description: "Remove a dependency between two issues.",
        subcommand: "dep rm",
        outputKey: "result",
        params: [
            {
                name: "issueId1",
                type: "string",
                description: "Dependent issue ID.",
                required: true,
                position: "leading",
                quote: false,
            },
            {
                name: "issueId2",
                type: "string",
                description: "Dependency issue ID.",
                required: true,
                position: "leading",
                quote: false,
            },
            {
                name: "type",
                type: "string",
                description: "Dependency type.",
                flag: "type",
            },
        ],
    },
    {
        name: "bd_dep_list",
        description: "List dependencies for an issue.",
        subcommand: "dep list",
        outputKey: "result",
        params: [
            {
                name: "issueId",
                type: "string",
                description: "Issue ID.",
                required: true,
                position: "trailing",
                quote: false,
            },
        ],
    },
    {
        name: "bd_duplicate",
        description: "Mark one issue as duplicate of another.",
        subcommand: "duplicate",
        outputKey: "result",
        params: [
            {
                name: "issueId1",
                type: "string",
                description: "Duplicate issue ID.",
                required: true,
                position: "leading",
                quote: false,
            },
            {
                name: "issueId2",
                type: "string",
                description: "Canonical issue ID.",
                required: true,
                position: "leading",
                quote: false,
            },
        ],
    },
    {
        name: "bd_duplicates",
        description: "Find and optionally link duplicate issues.",
        subcommand: "duplicates",
        outputKey: "result",
        params: [
            {
                name: "autoLink",
                type: "boolean",
                description: "Automatically link duplicates.",
                flag: "auto-link",
            },
        ],
    },
    passthrough("bd_epic", "epic", "Manage epics."),
    {
        name: "bd_graph",
        description: "Display the issue dependency graph.",
        subcommand: "graph",
        outputKey: "result",
        params: [
            {
                name: "query",
                type: "string",
                description: "Query filter.",
                flag: "query",
                quote: true,
            },
            {
                name: "depth",
                type: "number",
                description: "Graph depth.",
                flag: "depth",
            },
            {
                name: "format",
                type: "string",
                description: "Output format.",
                flag: "format",
            },
            {
                name: "output",
                type: "string",
                description: "Output file path.",
                flag: "output",
                quote: true,
            },
            {
                name: "focus",
                type: "string",
                description: "Focus issue ID.",
                flag: "focus",
            },
        ],
    },
    {
        name: "bd_supersede",
        description: "Mark one issue as superseded by another.",
        subcommand: "supersede",
        outputKey: "result",
        params: [
            {
                name: "issueId1",
                type: "string",
                description: "Superseded issue ID.",
                required: true,
                position: "leading",
                quote: false,
            },
            {
                name: "issueId2",
                type: "string",
                description: "Superseding issue ID.",
                required: true,
                position: "leading",
                quote: false,
            },
        ],
    },
    {
        name: "bd_swarm",
        description: "Manage swarms for structured epics.",
        subcommand: "swarm",
        outputKey: "result",
        params: [
            {
                name: "epicId",
                type: "string",
                description: "Epic ID.",
                required: true,
                position: "leading",
                quote: false,
            },
            {
                name: "command",
                type: "string",
                description: "Swarm subcommand.",
                required: true,
                position: "trailing",
                quote: false,
            },
        ],
    },
    {
        name: "bd_backup",
        description: "Back up the Beads database.",
        subcommand: "backup",
        outputKey: "result",
        params: [
            {
                name: "file",
                type: "string",
                description: "Backup file path.",
                flag: "file",
                quote: true,
            },
            {
                name: "format",
                type: "string",
                description: "Backup format.",
                flag: "format",
            },
        ],
    },
    passthrough("bd_branch", "branch", "Manage Git branches."),
    {
        name: "bd_export",
        description: "Export issues to a file.",
        subcommand: "export",
        outputKey: "result",
        params: [
            {
                name: "query",
                type: "string",
                description: "Export query filter.",
                flag: "query",
                quote: true,
            },
            {
                name: "format",
                type: "string",
                description: "Export format.",
                flag: "format",
            },
            {
                name: "output",
                type: "string",
                description: "Output file path.",
                flag: "output",
                quote: true,
            },
        ],
    },
    passthrough("bd_federation", "federation", "Manage peer federation."),
    {
        name: "bd_import",
        description: "Import issues from a file or stdin.",
        subcommand: "import",
        outputKey: "result",
        params: [
            {
                name: "file",
                type: "string",
                description: "Import file path.",
                flag: "file",
                quote: true,
            },
            {
                name: "format",
                type: "string",
                description: "Import format.",
                flag: "format",
            },
            {
                name: "stdin",
                type: "boolean",
                description: "Read import data from stdin.",
                flag: "stdin",
            },
        ],
    },
    {
        name: "bd_restore",
        description: "Restore compacted issue history from Dolt.",
        subcommand: "restore",
        outputKey: "result",
        params: [
            {
                name: "issueId",
                type: "string",
                description: "Issue ID.",
                required: true,
                position: "leading",
                quote: false,
            },
            {
                name: "file",
                type: "string",
                description: "Restore file path.",
                flag: "file",
                quote: true,
            },
            {
                name: "commit",
                type: "string",
                description: "Commit hash.",
                flag: "commit",
            },
        ],
    },
    passthrough("bd_vc", "vc", "Version control operations."),
    {
        name: "bd_sync",
        description: "Sync with git (bd sync).",
        subcommand: "sync",
        outputKey: "syncResult",
        params: [],
    },
    {
        name: "bd_bootstrap",
        description: "Non-destructive database setup.",
        subcommand: "bootstrap",
        outputKey: "result",
        params: [
            {
                name: "force",
                type: "boolean",
                description: "Force bootstrap.",
                flag: "force",
            },
        ],
    },
    {
        name: "bd_config_get",
        description: "Get a Beads configuration value.",
        subcommand: "config get",
        outputKey: "result",
        params: [
            {
                name: "key",
                type: "string",
                description: "Configuration key.",
                required: true,
                position: "trailing",
                quote: false,
            },
        ],
    },
    {
        name: "bd_config_set",
        description: "Set a Beads configuration value.",
        subcommand: "config set",
        outputKey: "result",
        params: [
            {
                name: "key",
                type: "string",
                description: "Configuration key.",
                required: true,
                position: "leading",
                quote: false,
            },
            {
                name: "value",
                type: "string",
                description: "Configuration value.",
                required: true,
                position: "trailing",
                quote: true,
            },
        ],
    },
    {
        name: "bd_context",
        description: "Show effective backend identity and repository context.",
        subcommand: "context",
        outputKey: "result",
        params: [],
    },
    {
        name: "bd_dolt_config",
        description: "Configure Dolt backend settings.",
        subcommand: "dolt",
        outputKey: "result",
        params: [
            {
                name: "key",
                type: "string",
                description: "Dolt config key.",
                required: true,
                flag: "config",
                quote: false,
            },
            {
                name: "value",
                type: "string",
                description: "Dolt config value.",
                required: true,
                position: "trailing",
                quote: true,
            },
        ],
    },
    {
        name: "bd_forget",
        description: "Remove a persistent memory entry.",
        subcommand: "forget",
        outputKey: "result",
        params: [
            {
                name: "memoryName",
                type: "string",
                description: "Memory name.",
                required: true,
                position: "trailing",
                quote: false,
            },
        ],
    },
    {
        name: "bd_hooks",
        description: "Manage Git hooks for Beads integration.",
        subcommand: "hooks",
        outputKey: "result",
        params: [
            {
                name: "install",
                type: "boolean",
                description: "Install hooks.",
                flag: "install",
            },
            {
                name: "uninstall",
                type: "boolean",
                description: "Uninstall hooks.",
                flag: "uninstall",
            },
        ],
    },
    {
        name: "bd_human",
        description: "Show essential commands for human users.",
        subcommand: "human",
        outputKey: "result",
        params: [],
    },
    {
        name: "bd_info",
        description: "Show detailed database information.",
        subcommand: "info",
        outputKey: "result",
        params: [],
    },
    {
        name: "bd_init",
        description: "Initialize Beads in the current directory.",
        subcommand: "init",
        outputKey: "result",
        params: [
            {
                name: "force",
                type: "boolean",
                description: "Force initialization.",
                flag: "force",
            },
            {
                name: "dbPath",
                type: "string",
                description: "Database path.",
                flag: "db-path",
                quote: true,
            },
            {
                name: "issuePrefix",
                type: "string",
                description: "Issue ID prefix.",
                flag: "issue-prefix",
            },
            {
                name: "worktreeBased",
                type: "boolean",
                description: "Use worktree-based layout.",
                flag: "worktree-based",
            },
        ],
    },
    passthrough("bd_kv", "kv", "Key-value store commands."),
    {
        name: "bd_memories",
        description: "List or search persistent memories.",
        subcommand: "memories",
        outputKey: "result",
        params: [
            {
                name: "search",
                type: "string",
                description: "Search query.",
                flag: "search",
                quote: true,
            },
            {
                name: "list",
                type: "boolean",
                description: "List memories.",
                flag: "list",
            },
        ],
    },
    {
        name: "bd_onboard",
        description: "Output minimal agent onboarding snippet.",
        subcommand: "onboard",
        outputKey: "result",
        params: [],
    },
    {
        name: "bd_prime",
        description: "Output AI-optimized workflow context.",
        subcommand: "prime",
        outputKey: "result",
        params: [],
    },
    {
        name: "bd_quickstart",
        description: "Show Beads quick start guide.",
        subcommand: "quickstart",
        outputKey: "result",
        params: [],
    },
    {
        name: "bd_recall",
        description: "Retrieve a stored memory.",
        subcommand: "recall",
        outputKey: "result",
        params: [
            {
                name: "memoryName",
                type: "string",
                description: "Memory name.",
                required: true,
                position: "trailing",
                quote: false,
            },
        ],
    },
    {
        name: "bd_remember",
        description: "Store a persistent memory entry.",
        subcommand: "remember",
        outputKey: "result",
        params: [
            {
                name: "memoryName",
                type: "string",
                description: "Memory name.",
                required: true,
                position: "leading",
                quote: false,
            },
            {
                name: "memoryContent",
                type: "string",
                description: "Memory content.",
                required: true,
                position: "trailing",
                quote: true,
            },
        ],
    },
    {
        name: "bd_setup",
        description: "Set up AI editor integration.",
        subcommand: "setup",
        outputKey: "result",
        params: [
            {
                name: "editor",
                type: "string",
                description: "Editor name.",
                flag: "editor",
            },
        ],
    },
    {
        name: "bd_where",
        description: "Show active Beads database and Git paths.",
        subcommand: "where",
        outputKey: "result",
        params: [],
    },
    {
        name: "bd_batch",
        description: "Run multiple write operations in one transaction.",
        subcommand: "batch",
        outputKey: "result",
        params: [
            {
                name: "command",
                type: "string",
                description: "Batch command payload.",
                required: true,
                position: "trailing",
                quote: false,
            },
        ],
    },
    {
        name: "bd_compact",
        description: "Squash old Dolt commits.",
        subcommand: "compact",
        outputKey: "result",
        params: [
            {
                name: "dryRun",
                type: "boolean",
                description: "Dry run only.",
                flag: "dry-run",
            },
            {
                name: "force",
                type: "boolean",
                description: "Force compact.",
                flag: "force",
            },
        ],
    },
    {
        name: "bd_doctor",
        description: "Check and fix Beads installation health.",
        subcommand: "doctor",
        outputKey: "result",
        params: [
            {
                name: "fix",
                type: "boolean",
                description: "Attempt fixes.",
                flag: "fix",
            },
        ],
    },
    {
        name: "bd_flatten",
        description: "Squash all Dolt history into one commit.",
        subcommand: "flatten",
        outputKey: "result",
        params: [
            {
                name: "dryRun",
                type: "boolean",
                description: "Dry run only.",
                flag: "dry-run",
            },
            {
                name: "force",
                type: "boolean",
                description: "Force flatten.",
                flag: "force",
            },
        ],
    },
    {
        name: "bd_gc",
        description: "Run Beads garbage collection.",
        subcommand: "gc",
        outputKey: "result",
        params: [
            {
                name: "dryRun",
                type: "boolean",
                description: "Dry run only.",
                flag: "dry-run",
            },
            {
                name: "full",
                type: "boolean",
                description: "Full GC.",
                flag: "full",
            },
        ],
    },
    {
        name: "bd_migrate",
        description: "Perform database schema migrations.",
        subcommand: "migrate",
        outputKey: "result",
        params: [
            {
                name: "to",
                type: "string",
                description: "Target schema version.",
                required: true,
                flag: "to",
            },
            {
                name: "from",
                type: "string",
                description: "Source schema version.",
                flag: "from",
            },
        ],
    },
    {
        name: "bd_ping",
        description: "Check database connectivity.",
        subcommand: "ping",
        outputKey: "result",
        params: [],
    },
    {
        name: "bd_preflight",
        description: "Show PR readiness checklist.",
        subcommand: "preflight",
        outputKey: "result",
        params: [],
    },
    {
        name: "bd_prune",
        description: "Delete old closed issues.",
        subcommand: "prune",
        outputKey: "result",
        params: [
            {
                name: "days",
                type: "number",
                description: "Age threshold in days.",
                flag: "days",
            },
            {
                name: "dryRun",
                type: "boolean",
                description: "Dry run only.",
                flag: "dry-run",
            },
            {
                name: "force",
                type: "boolean",
                description: "Force prune.",
                flag: "force",
            },
        ],
    },
    {
        name: "bd_purge",
        description: "Delete closed ephemeral issues.",
        subcommand: "purge",
        outputKey: "result",
        params: [
            {
                name: "days",
                type: "number",
                description: "Age threshold in days.",
                flag: "days",
            },
            {
                name: "dryRun",
                type: "boolean",
                description: "Dry run only.",
                flag: "dry-run",
            },
            {
                name: "force",
                type: "boolean",
                description: "Force purge.",
                flag: "force",
            },
        ],
    },
    {
        name: "bd_rename_prefix",
        description: "Rename issue ID prefix for all issues.",
        subcommand: "rename-prefix",
        outputKey: "result",
        params: [
            {
                name: "oldPrefix",
                type: "string",
                description: "Old prefix.",
                required: true,
                position: "leading",
                quote: false,
            },
            {
                name: "newPrefix",
                type: "string",
                description: "New prefix.",
                required: true,
                position: "trailing",
                quote: false,
            },
        ],
    },
    {
        name: "bd_rules",
        description: "Audit and compact Claude rules.",
        subcommand: "rules",
        outputKey: "result",
        params: [
            {
                name: "audit",
                type: "boolean",
                description: "Audit rules.",
                flag: "audit",
            },
            {
                name: "compact",
                type: "boolean",
                description: "Compact rules.",
                flag: "compact",
            },
        ],
    },
    {
        name: "bd_sql",
        description: "Execute raw SQL against the Beads database.",
        subcommand: "sql",
        outputKey: "result",
        params: [
            {
                name: "sqlQuery",
                type: "string",
                description: "SQL query.",
                required: true,
                position: "trailing",
                quote: true,
            },
        ],
    },
    {
        name: "bd_upgrade",
        description: "Check for and manage Beads upgrades.",
        subcommand: "upgrade",
        outputKey: "result",
        params: [
            {
                name: "check",
                type: "boolean",
                description: "Check for upgrades.",
                flag: "check",
            },
            {
                name: "install",
                type: "boolean",
                description: "Install upgrade.",
                flag: "install",
            },
            {
                name: "force",
                type: "boolean",
                description: "Force upgrade.",
                flag: "force",
            },
        ],
    },
    passthrough("bd_worktree", "worktree", "Manage Git worktrees."),
    passthrough("bd_admin", "admin", "Administrative database commands."),
    {
        name: "bd_jira",
        description: "Jira integration sync commands.",
        subcommand: "jira",
        outputKey: "result",
        params: [
            {
                name: "sync",
                type: "boolean",
                description: "Run Jira sync.",
                flag: "sync",
            },
            {
                name: "project",
                type: "string",
                description: "Jira project key.",
                flag: "project",
            },
            {
                name: "issue",
                type: "string",
                description: "Issue ID filter.",
                flag: "issue",
            },
        ],
    },
    {
        name: "bd_linear",
        description: "Linear integration sync commands.",
        subcommand: "linear",
        outputKey: "result",
        params: [
            {
                name: "sync",
                type: "boolean",
                description: "Run Linear sync.",
                flag: "sync",
            },
            {
                name: "issue",
                type: "string",
                description: "Issue ID filter.",
                flag: "issue",
            },
        ],
    },
    passthrough("bd_repo", "repo", "Manage multi-repository configurations."),
    passthrough("bd_ado", "ado", "Azure DevOps integration commands."),
    {
        name: "bd_audit",
        description: "Record and label agent interactions.",
        subcommand: "audit",
        outputKey: "result",
        params: [
            {
                name: "record",
                type: "string",
                description: "Audit event record.",
                flag: "record",
                quote: true,
            },
            {
                name: "label",
                type: "string",
                description: "Audit label.",
                flag: "label",
            },
            {
                name: "file",
                type: "string",
                description: "Audit file path.",
                flag: "file",
                quote: true,
            },
        ],
    },
    {
        name: "bd_blocked",
        description: "Show currently blocked issues.",
        subcommand: "blocked",
        outputKey: "result",
        params: [],
    },
    {
        name: "bd_completion",
        description: "Generate shell autocompletion script.",
        subcommand: "completion",
        outputKey: "result",
        params: [
            {
                name: "shell",
                type: "string",
                description: "Target shell (bash, zsh, fish).",
                required: true,
                position: "trailing",
                quote: false,
            },
        ],
    },
    {
        name: "bd_cook",
        description: "Compile a workflow formula into a proto.",
        subcommand: "cook",
        outputKey: "result",
        params: [
            {
                name: "formula",
                type: "string",
                description: "Workflow formula.",
                required: true,
                position: "leading",
                quote: true,
            },
            {
                name: "output",
                type: "string",
                description: "Output file path.",
                flag: "output",
                quote: true,
            },
            {
                name: "ephemeral",
                type: "boolean",
                description: "Create ephemeral proto.",
                flag: "ephemeral",
            },
        ],
    },
    {
        name: "bd_defer",
        description: "Defer issues for later consideration.",
        subcommand: "defer",
        outputKey: "result",
        params: [issueIds()],
    },
    passthrough("bd_formula", "formula", "Manage workflow formulas."),
    passthrough("bd_github", "github", "GitHub integration commands."),
    {
        name: "bd_help",
        description: "Display help for bd commands.",
        subcommand: "help",
        outputKey: "result",
        params: [
            {
                name: "command",
                type: "string",
                description: "Command to show help for.",
                position: "trailing",
                quote: false,
            },
        ],
    },
    {
        name: "bd_init_safety",
        description: "Explain bd init safety semantics.",
        subcommand: "init-safety",
        outputKey: "result",
        params: [],
    },
    {
        name: "bd_mail",
        description: "Delegate to mail provider commands.",
        subcommand: "mail",
        outputKey: "result",
        params: [
            {
                name: "list",
                type: "boolean",
                description: "List mail.",
                flag: "list",
            },
            {
                name: "send",
                type: "boolean",
                description: "Send mail.",
                flag: "send",
            },
        ],
    },
    passthrough("bd_mol", "mol", "Manage molecule templates."),
    {
        name: "bd_notion",
        description: "Notion integration sync commands.",
        subcommand: "notion",
        outputKey: "result",
        params: [
            {
                name: "sync",
                type: "boolean",
                description: "Run Notion sync.",
                flag: "sync",
            },
            {
                name: "databaseId",
                type: "string",
                description: "Notion database ID.",
                flag: "database-id",
            },
            {
                name: "issue",
                type: "string",
                description: "Issue ID filter.",
                flag: "issue",
            },
        ],
    },
    {
        name: "bd_orphans",
        description: "Identify orphaned open issues referenced in commits.",
        subcommand: "orphans",
        outputKey: "result",
        params: [],
    },
    {
        name: "bd_ready",
        description: "Show ready work with no blockers.",
        subcommand: "ready",
        outputKey: "result",
        params: [
            {
                name: "query",
                type: "string",
                description: "Query filter.",
                flag: "query",
                quote: true,
            },
            {
                name: "assignee",
                type: "string",
                description: "Assignee filter.",
                flag: "assignee",
            },
        ],
    },
    {
        name: "bd_rename",
        description: "Rename an issue ID.",
        subcommand: "rename",
        outputKey: "result",
        params: [
            {
                name: "issueId",
                type: "string",
                description: "Current issue ID.",
                required: true,
                position: "leading",
                quote: false,
            },
            {
                name: "newId",
                type: "string",
                description: "New issue ID.",
                required: true,
                position: "trailing",
                quote: false,
            },
        ],
    },
    {
        name: "bd_ship",
        description: "Publish a capability for cross-project dependencies.",
        subcommand: "ship",
        outputKey: "result",
        params: [
            {
                name: "capability",
                type: "string",
                description: "Capability name.",
                required: true,
                position: "leading",
                quote: false,
            },
            {
                name: "version",
                type: "string",
                description: "Capability version.",
                flag: "version",
            },
        ],
    },
    {
        name: "bd_undefer",
        description: "Undefer issues back to open state.",
        subcommand: "undefer",
        outputKey: "result",
        params: [issueIds()],
    },
];

export const EXPECTED_TOOL_NAMES = BD_TOOL_SPECS.map((spec) => spec.name);

export const BD_TOOL_TEST_CASES: ToolTestCase[] = [
    { tool: "bd_version", command: "--version" },
    {
        tool: "bd_assign",
        args: { issueIds: ["A-1"], actor: "alice" },
        command: "assign A-1 --actor alice",
    },
    {
        tool: "bd_children",
        args: { issueId: "EPIC-1" },
        command: "children EPIC-1",
    },
    {
        tool: "bd_close",
        args: { issueIds: ["A-1", "A-2"] },
        command: "close A-1 A-2",
    },
    {
        tool: "bd_comment",
        args: { issueId: "A-1", body: "Looks good" },
        command: 'comment A-1 --body "Looks good"',
    },
    {
        tool: "bd_comments",
        args: { issueId: "A-1", limit: 5 },
        command: "comments A-1 --limit 5",
    },
    {
        tool: "bd_create",
        args: { title: "Task", type: "task", description: "Do it" },
        command: 'create --title "Task" --type task --description "Do it"',
    },
    {
        tool: "bd_create",
        args: {},
        command: "create --title 'New Issue Creation'",
    },
    {
        tool: "bd_create",
        args: { parent: "EPIC-1" },
        command: "create --parent EPIC-1",
    },
    {
        tool: "bd_create",
        args: { batch: true },
        command: "create --batch",
     },
    { tool: "bd_create_form", command: "create-form" },
    {
        tool: "bd_delete",
        args: { issueIds: ["A-1"] },
        command: "delete A-1",
    },
    {
        tool: "bd_edit",
        args: { issueId: "A-1", field: "title", value: "New" },
        command: 'edit A-1 --field title --value "New"',
    },
    {
        tool: "bd_gate",
        args: { issueIds: ["A-1"], condition: "all-closed" },
        command: 'gate A-1 --condition "all-closed"',
    },
    {
        tool: "bd_label",
        args: { issueIds: ["A-1"], add: ["bug"] },
        command: "label A-1 --add bug",
    },
    {
        tool: "bd_link",
        args: { issueId1: "A-1", issueId2: "A-2", relation: "blocks" },
        command: "link A-1 A-2 --relation blocks",
    },
    {
        tool: "bd_list",
        args: { status: "open", limit: 10 },
        command: "list --status open --limit 10",
    },
    {
        tool: "bd_merge_slot",
        args: { issueIds: ["A-1"], condition: "ready" },
        command: 'merge-slot A-1 --condition "ready"',
    },
    {
        tool: "bd_note",
        args: { issueId: "A-1", noteText: "FYI" },
        command: 'note A-1 "FYI"',
    },
    {
        tool: "bd_priority",
        args: { issueIds: ["A-1"], priority: "P1" },
        command: "priority A-1 --priority P1",
    },
    {
        tool: "bd_promote",
        args: { issueId: "W-1" },
        command: "promote W-1",
    },
    { tool: "bd_q", command: "q" },
    {
        tool: "bd_query",
        args: { queryString: "status:open", limit: 3 },
        command: 'query "status:open" --limit 3',
    },
    {
        tool: "bd_reopen",
        args: { issueIds: ["A-1"] },
        command: "reopen A-1",
    },
    {
        tool: "bd_search",
        args: { textQuery: "login bug", status: "open" },
        command: 'search "login bug" --status open',
    },
    {
        tool: "bd_set_state",
        args: { issueIds: ["A-1"], state: "in_progress" },
        command: "set-state A-1 --state in_progress",
    },
    {
        tool: "bd_show",
        args: { issueId: "A-1", format: "json" },
        command: 'show "A-1" --format json',
    },
    {
        tool: "bd_show",
        args: {},
        throws: "issueId is required to show an issue.",
    },
    {
        tool: "bd_state",
        args: { dimension: "status", list: true },
        command: "state status --list",
    },
    {
        tool: "bd_tag",
        args: { issueIds: ["A-1"], remove: ["old"] },
        command: "tag A-1 --remove old",
    },
    {
        tool: "bd_todo",
        args: { add: "Write tests" },
        command: 'todo --add "Write tests"',
    },
    {
        tool: "bd_update",
        args: { issueIds: ["A-1"], field: "status", value: "closed" },
        command: 'update A-1 --field status --value "closed"',
    },
    {
        tool: "bd_count",
        args: { status: "open" },
        command: "count --status open",
    },
    {
        tool: "bd_diff",
        args: { base: "main", head: "feature" },
        command: "diff --base main --head feature",
    },
    {
        tool: "bd_find_duplicates",
        args: { autoMerge: true },
        command: "find-duplicates --auto-merge",
    },
    {
        tool: "bd_history",
        args: { issueId: "A-1" },
        command: "history A-1",
    },
    { tool: "bd_lint", args: { fix: true }, command: "lint --fix" },
    {
        tool: "bd_stale",
        args: { days: 30 },
        command: "stale --days 30",
    },
    {
        tool: "bd_status",
        args: { format: "json" },
        command: "status --format json",
    },
    { tool: "bd_statuses", args: { list: true }, command: "statuses --list" },
    { tool: "bd_types", args: { list: true }, command: "types --list" },
    {
        tool: "bd_dep_add",
        args: { issueId1: "A-2", issueId2: "A-1", type: "blocks" },
        command: "dep add A-2 A-1 --type blocks",
    },
    {
        tool: "bd_dep_rm",
        args: { issueId1: "A-2", issueId2: "A-1" },
        command: "dep rm A-2 A-1",
    },
    {
        tool: "bd_dep_list",
        args: { issueId: "A-1" },
        command: "dep list A-1",
    },
    {
        tool: "bd_duplicate",
        args: { issueId1: "A-2", issueId2: "A-1" },
        command: "duplicate A-2 A-1",
    },
    {
        tool: "bd_duplicates",
        args: { autoLink: true },
        command: "duplicates --auto-link",
    },
    {
        tool: "bd_epic",
        args: { command: "list" },
        command: "epic list",
    },
    {
        tool: "bd_graph",
        args: { depth: 2, focus: "A-1" },
        command: "graph --depth 2 --focus A-1",
    },
    {
        tool: "bd_supersede",
        args: { issueId1: "A-1", issueId2: "A-2" },
        command: "supersede A-1 A-2",
    },
    {
        tool: "bd_swarm",
        args: { epicId: "E-1", command: "status" },
        command: "swarm E-1 status",
    },
    {
        tool: "bd_backup",
        args: { file: "/tmp/backup.jsonl" },
        command: 'backup --file "/tmp/backup.jsonl"',
    },
    {
        tool: "bd_branch",
        args: { command: "list" },
        command: "branch list",
    },
    {
        tool: "bd_export",
        args: { format: "jsonl", output: "/tmp/out.jsonl" },
        command: 'export --format jsonl --output "/tmp/out.jsonl"',
    },
    {
        tool: "bd_federation",
        args: { command: "status" },
        command: "federation status",
    },
    {
        tool: "bd_import",
        args: { stdin: true },
        command: "import --stdin",
    },
    {
        tool: "bd_restore",
        args: { issueId: "A-1", commit: "abc123" },
        command: "restore A-1 --commit abc123",
    },
    {
        tool: "bd_vc",
        args: { command: "log" },
        command: "vc log",
    },
    { tool: "bd_sync", command: "sync" },
    { tool: "bd_bootstrap", args: { force: true }, command: "bootstrap --force" },
    {
        tool: "bd_config_get",
        args: { key: "db.path" },
        command: "config get db.path",
    },
    {
        tool: "bd_config_set",
        args: { key: "db.path", value: "/tmp/db" },
        command: 'config set db.path "/tmp/db"',
    },
    { tool: "bd_context", command: "context" },
    {
        tool: "bd_dolt_config",
        args: { key: "auto-commit", value: "on" },
        command: 'dolt --config auto-commit "on"',
    },
    {
        tool: "bd_forget",
        args: { memoryName: "old-fact" },
        command: "forget old-fact",
    },
    {
        tool: "bd_hooks",
        args: { install: true },
        command: "hooks --install",
    },
    { tool: "bd_human", command: "human" },
    { tool: "bd_info", command: "info" },
    {
        tool: "bd_init",
        args: { issuePrefix: "proj" },
        command: "init --issue-prefix proj",
    },
    { tool: "bd_kv", args: { command: "get foo" }, command: "kv get foo" },
    {
        tool: "bd_memories",
        args: { search: "architecture" },
        command: 'memories --search "architecture"',
    },
    { tool: "bd_onboard", command: "onboard" },
    { tool: "bd_prime", command: "prime" },
    { tool: "bd_quickstart", command: "quickstart" },
    {
        tool: "bd_recall",
        args: { memoryName: "fact" },
        command: "recall fact",
    },
    {
        tool: "bd_remember",
        args: { memoryName: "fact", memoryContent: "value" },
        command: 'remember fact "value"',
    },
    {
        tool: "bd_setup",
        args: { editor: "cursor" },
        command: "setup --editor cursor",
    },
    { tool: "bd_where", command: "where" },
    {
        tool: "bd_batch",
        args: { command: "close A-1" },
        command: "batch close A-1",
    },
    {
        tool: "bd_compact",
        args: { dryRun: true },
        command: "compact --dry-run",
    },
    { tool: "bd_doctor", args: { fix: true }, command: "doctor --fix" },
    {
        tool: "bd_flatten",
        args: { force: true },
        command: "flatten --force",
    },
    { tool: "bd_gc", args: { full: true }, command: "gc --full" },
    {
        tool: "bd_migrate",
        args: { to: "2", from: "1" },
        command: "migrate --to 2 --from 1",
    },
    { tool: "bd_ping", command: "ping" },
    { tool: "bd_preflight", command: "preflight" },
    {
        tool: "bd_prune",
        args: { days: 90, dryRun: true },
        command: "prune --days 90 --dry-run",
    },
    {
        tool: "bd_purge",
        args: { days: 30, force: true },
        command: "purge --days 30 --force",
    },
    {
        tool: "bd_rename_prefix",
        args: { oldPrefix: "OLD", newPrefix: "NEW" },
        command: "rename-prefix OLD NEW",
    },
    {
        tool: "bd_rules",
        args: { audit: true },
        command: "rules --audit",
    },
    {
        tool: "bd_sql",
        args: { sqlQuery: "select 1" },
        command: 'sql "select 1"',
    },
    {
        tool: "bd_upgrade",
        args: { check: true },
        command: "upgrade --check",
    },
    {
        tool: "bd_worktree",
        args: { command: "list" },
        command: "worktree list",
    },
    {
        tool: "bd_admin",
        args: { command: "status" },
        command: "admin status",
    },
    {
        tool: "bd_jira",
        args: { sync: true, project: "ENG" },
        command: "jira --sync --project ENG",
    },
    {
        tool: "bd_linear",
        args: { sync: true, issue: "A-1" },
        command: "linear --sync --issue A-1",
    },
    {
        tool: "bd_repo",
        args: { command: "list" },
        command: "repo list",
    },
    {
        tool: "bd_ado",
        args: { command: "sync" },
        command: "ado sync",
    },
    {
        tool: "bd_audit",
        args: { record: "session-start" },
        command: 'audit --record "session-start"',
    },
    { tool: "bd_blocked", command: "blocked" },
    {
        tool: "bd_completion",
        args: { shell: "bash" },
        command: "completion bash",
    },
    {
        tool: "bd_cook",
        args: { formula: "deploy", ephemeral: true },
        command: 'cook "deploy" --ephemeral',
    },
    {
        tool: "bd_defer",
        args: { issueIds: ["A-1"] },
        command: "defer A-1",
    },
    {
        tool: "bd_formula",
        args: { command: "list" },
        command: "formula list",
    },
    {
        tool: "bd_github",
        args: { command: "pr list" },
        command: "github pr list",
    },
    {
        tool: "bd_help",
        args: { command: "create" },
        command: "help create",
    },
    { tool: "bd_init_safety", command: "init-safety" },
    { tool: "bd_mail", args: { list: true }, command: "mail --list" },
    {
        tool: "bd_mol",
        args: { command: "list" },
        command: "mol list",
    },
    {
        tool: "bd_notion",
        args: { sync: true, databaseId: "db-1" },
        command: "notion --sync --database-id db-1",
    },
    { tool: "bd_orphans", command: "orphans" },
    {
        tool: "bd_ready",
        args: { assignee: "alice" },
        command: "ready --assignee alice",
    },
    {
        tool: "bd_rename",
        args: { issueId: "A-1", newId: "A-99" },
        command: "rename A-1 A-99",
    },
    {
        tool: "bd_ship",
        args: { capability: "auth", version: "1.0.0" },
        command: "ship auth --version 1.0.0",
    },
    {
        tool: "bd_undefer",
        args: { issueIds: ["A-1"] },
        command: "undefer A-1",
    },
];

export function getToolSpec(name: string): BdToolSpec {
    const spec = BD_TOOL_SPECS.find((entry) => entry.name === name);
    if (!spec) {
        throw new Error(`Unknown tool spec: ${name}`);
    }
    return spec;
}
