import type { BdToolSpec, ToolTestCase } from "./bdTypes";
import { issueIds, listFilterParams, passthrough, sortParams } from "./bdCliShared";

export const BD_TOOL_SPECS: BdToolSpec[] = [
    {
        name: "bd_version",
        description: "Get the current version of the Beads CLI (bd).",
        subcommand: "--version",
        params: [],
        outputKey: "version",
        includeGlobalFlags: false,
    },
    // --- Working with issues ---
    {
        name: "bd_close",
        description: "Close one or more issues.",
        subcommand: "close",
        outputKey: "result",
        params: [issueIds()],
    },
    {
        name: "bd_comment",
        description: "Add a comment to an issue (alias for bd comments add).",
        subcommand: "comment",
        outputKey: "result",
        params: [
            {
                name: "issueId",
                type: "string",
                description: "Issue ID.",
                required: true,
                position: "leading",
                quote: false,
            },
            {
                name: "text",
                type: "string",
                description: "Comment text.",
                position: "leading",
                quote: true,
            },
            {
                name: "author",
                type: "string",
                description: "Comment author.",
                shortFlag: "a",
            },
            {
                name: "file",
                type: "string",
                description: "Read comment text from file.",
                shortFlag: "f",
                quote: true,
            },
        ],
    },
    {
        name: "bd_comments",
        description: "List comments on an issue.",
        subcommand: "comments",
        outputKey: "result",
        params: [
            {
                name: "issueId",
                type: "string",
                description: "Issue ID.",
                required: true,
                position: "trailing",
                quote: false,
            },
        ],
    },
    {
        name: "bd_comments_add",
        description: "Add a comment to an issue.",
        subcommand: "comments add",
        outputKey: "result",
        params: [
            {
                name: "issueId",
                type: "string",
                description: "Issue ID.",
                required: true,
                position: "leading",
                quote: false,
            },
            {
                name: "text",
                type: "string",
                description: "Comment text.",
                position: "leading",
                quote: true,
            },
            {
                name: "author",
                type: "string",
                description: "Comment author.",
                shortFlag: "a",
            },
            {
                name: "file",
                type: "string",
                description: "Read comment text from file.",
                shortFlag: "f",
                quote: true,
            },
        ],
    },
    {
        name: "bd_create",
        description: "Create a new issue (or multiple from a markdown file).",
        subcommand: "create",
        outputKey: "creationResult",
        params: [
            {
                name: "title",
                type: "string",
                description: "Issue title.",
                flag: "title",
                quote: true,
            },
            {
                name: "type",
                type: "string",
                description: "Issue type (bug, feature, task, epic, chore, etc.).",
                shortFlag: "t",
            },
            {
                name: "description",
                type: "string",
                description: "Issue description.",
                shortFlag: "d",
                quote: true,
            },
            {
                name: "parent",
                type: "string",
                description: "Parent issue ID for hierarchical child.",
                flag: "parent",
            },
            {
                name: "assignee",
                type: "string",
                description: "Assignee.",
                shortFlag: "a",
            },
            {
                name: "priority",
                type: "string",
                description: "Priority (0-4 or P0-P4).",
                shortFlag: "p",
            },
            {
                name: "labels",
                type: "string[]",
                description: "Labels (comma-separated).",
                shortFlag: "l",
                joinWith: ",",
            },
            {
                name: "acceptance",
                type: "string",
                description: "Acceptance criteria.",
                flag: "acceptance",
                quote: true,
            },
            {
                name: "design",
                type: "string",
                description: "Design notes.",
                flag: "design",
                quote: true,
            },
            {
                name: "deps",
                type: "string[]",
                description: "Dependencies (type:id or id).",
                flag: "deps",
                joinWith: ",",
            },
            {
                name: "file",
                type: "string",
                description: "Create multiple issues from markdown file.",
                shortFlag: "f",
                quote: true,
            },
            {
                name: "graph",
                type: "string",
                description: "Batch-create issues from YAML/JSON dependency graph file (bd 1.0+).",
                flag: "graph",
                quote: true,
            },
            {
                name: "bodyFile",
                type: "string",
                description: "Read description from file.",
                flag: "body-file",
                quote: true,
            },
            {
                name: "prefix",
                type: "string",
                description: "Create issue in rig by prefix.",
                flag: "prefix",
            },
            {
                name: "silent",
                type: "boolean",
                description: "Output only the issue ID.",
                flag: "silent",
            },
        ],
    },
    {
        name: "bd_create_form",
        description: "Create a new issue using an interactive form.",
        subcommand: "create-form",
        outputKey: "result",
        params: [],
    },
    {
        name: "bd_delete",
        description: "Delete one or more issues.",
        subcommand: "delete",
        outputKey: "result",
        params: [issueIds()],
    },
    {
        name: "bd_edit",
        description: "Edit an issue field in $EDITOR (description, title, design, notes, acceptance).",
        subcommand: "edit",
        outputKey: "result",
        params: [
            {
                name: "issueId",
                type: "string",
                description: "Issue ID.",
                required: true,
                position: "trailing",
                quote: false,
            },
            {
                name: "title",
                type: "boolean",
                description: "Edit the title.",
                flag: "title",
            },
            {
                name: "description",
                type: "boolean",
                description: "Edit the description (default).",
                flag: "description",
            },
            {
                name: "design",
                type: "boolean",
                description: "Edit design notes.",
                flag: "design",
            },
            {
                name: "notes",
                type: "boolean",
                description: "Edit notes.",
                flag: "notes",
            },
            {
                name: "acceptance",
                type: "boolean",
                description: "Edit acceptance criteria.",
                flag: "acceptance",
            },
        ],
    },
    {
        name: "bd_update",
        description: "Update one or more issues programmatically (title, status, priority, parent, labels, etc.).",
        subcommand: "update",
        outputKey: "result",
        params: [
            issueIds("Issue IDs to update.", false),
            {
                name: "title",
                type: "string",
                description: "New title.",
                flag: "title",
                quote: true,
            },
            {
                name: "description",
                type: "string",
                description: "New description.",
                shortFlag: "d",
                quote: true,
            },
            {
                name: "status",
                type: "string",
                description: "New status.",
                shortFlag: "s",
            },
            {
                name: "type",
                type: "string",
                description: "New type.",
                shortFlag: "t",
            },
            {
                name: "priority",
                type: "string",
                description: "New priority.",
                shortFlag: "p",
            },
            {
                name: "assignee",
                type: "string",
                description: "New assignee.",
                shortFlag: "a",
            },
            {
                name: "parent",
                type: "string",
                description: "New parent issue ID (empty string to remove).",
                flag: "parent",
            },
            {
                name: "notes",
                type: "string",
                description: "Additional notes.",
                flag: "notes",
                quote: true,
            },
            {
                name: "design",
                type: "string",
                description: "Design notes.",
                flag: "design",
                quote: true,
            },
            {
                name: "acceptance",
                type: "string",
                description: "Acceptance criteria.",
                flag: "acceptance",
                quote: true,
            },
            {
                name: "addLabel",
                type: "string[]",
                description: "Labels to add.",
                flag: "add-label",
                joinWith: " ",
            },
            {
                name: "removeLabel",
                type: "string[]",
                description: "Labels to remove.",
                flag: "remove-label",
                joinWith: " ",
            },
            {
                name: "setLabels",
                type: "string[]",
                description: "Set labels, replacing all existing.",
                flag: "set-labels",
                joinWith: " ",
            },
            {
                name: "claim",
                type: "boolean",
                description: "Atomically claim the issue.",
                flag: "claim",
            },
        ],
    },
    {
        name: "bd_link",
        description:
            "Link two issues (bd 1.0+). Shorthand for dep add. Default type is blocks; use type parent-child for hierarchy. Example: link child parent --type parent-child.",
        subcommand: "link",
        outputKey: "result",
        params: [
            {
                name: "issueId1",
                type: "string",
                description: "First issue ID (the dependent issue).",
                required: true,
                position: "leading",
                quote: false,
            },
            {
                name: "issueId2",
                type: "string",
                description: "Second issue ID (the dependency target).",
                required: true,
                position: "leading",
                quote: false,
            },
            {
                name: "type",
                type: "string",
                description: "Dependency type: blocks, tracks, related, parent-child, discovered-from.",
                shortFlag: "t",
            },
        ],
    },
    {
        name: "bd_batch",
        description:
            "Run multiple write operations in one transaction (bd 1.0+). Provide a script file via file.",
        subcommand: "batch",
        outputKey: "result",
        params: [
            {
                name: "file",
                type: "string",
                description: "Batch script file (one command per line: close, update, create, dep add/remove).",
                required: true,
                shortFlag: "f",
                quote: true,
            },
            {
                name: "dryRun",
                type: "boolean",
                description: "Parse and echo commands without executing.",
                flag: "dry-run",
            },
            {
                name: "message",
                type: "string",
                description: "DOLT_COMMIT message for the batch.",
                shortFlag: "m",
                quote: true,
            },
        ],
    },
    {
        name: "bd_defer",
        description: "Defer one or more issues for later.",
        subcommand: "defer",
        outputKey: "result",
        params: [issueIds()],
    },
    {
        name: "bd_undefer",
        description: "Undefer one or more issues (restore to open).",
        subcommand: "undefer",
        outputKey: "result",
        params: [issueIds()],
    },
    {
        name: "bd_reopen",
        description: "Reopen one or more closed issues.",
        subcommand: "reopen",
        outputKey: "result",
        params: [issueIds()],
    },
    {
        name: "bd_search",
        description: "Search issues by text query.",
        subcommand: "search",
        outputKey: "result",
        params: [
            {
                name: "query",
                type: "string",
                description: "Search query (positional or use --query).",
                position: "leading",
                quote: true,
            },
            {
                name: "status",
                type: "string",
                description: "Filter by status.",
                shortFlag: "s",
            },
            {
                name: "type",
                type: "string",
                description: "Filter by type.",
                shortFlag: "t",
            },
            ...sortParams,
            {
                name: "limit",
                type: "number",
                description: "Limit results.",
                shortFlag: "n",
            },
        ],
    },
    {
        name: "bd_set_state",
        description: "Set operational state on an issue (creates event + label).",
        subcommand: "set-state",
        outputKey: "result",
        params: [
            {
                name: "issueId",
                type: "string",
                description: "Issue ID.",
                required: true,
                position: "leading",
                quote: false,
            },
            {
                name: "state",
                type: "string",
                description: "State as dimension=value (e.g. patrol=muted).",
                required: true,
                position: "leading",
                quote: false,
            },
            {
                name: "reason",
                type: "string",
                description: "Reason for the state change.",
                flag: "reason",
                quote: true,
            },
        ],
    },
    {
        name: "bd_show",
        description: "Show issue details.",
        subcommand: "show",
        outputKey: "result",
        params: [
            issueIds("Issue IDs to show.", false),
            {
                name: "refs",
                type: "boolean",
                description: "Show issues that reference this issue.",
                flag: "refs",
            },
            {
                name: "children",
                type: "boolean",
                description: "Show only children of this issue.",
                flag: "children",
            },
            {
                name: "short",
                type: "boolean",
                description: "Show compact one-line output.",
                flag: "short",
            },
            {
                name: "long",
                type: "boolean",
                description: "Show all available fields.",
                flag: "long",
            },
            {
                name: "thread",
                type: "boolean",
                description: "Show full conversation thread (messages).",
                flag: "thread",
            },
            {
                name: "current",
                type: "boolean",
                description: "Show the currently active issue.",
                flag: "current",
            },
            {
                name: "watch",
                type: "boolean",
                description: "Watch for changes and auto-refresh.",
                shortFlag: "w",
            },
            {
                name: "asOf",
                type: "string",
                description: "Show issue at a specific commit hash or branch.",
                flag: "as-of",
            },
            {
                name: "localTime",
                type: "boolean",
                description: "Show timestamps in local time.",
                flag: "local-time",
            },
        ],
    },
    {
        name: "bd_state",
        description: "Query the current value of a state dimension.",
        subcommand: "state",
        outputKey: "result",
        params: [
            {
                name: "issueId",
                type: "string",
                description: "Issue ID.",
                required: true,
                position: "leading",
                quote: false,
            },
            {
                name: "dimension",
                type: "string",
                description: "State dimension to query.",
                position: "trailing",
                quote: false,
            },
        ],
    },
    {
        name: "bd_q",
        description: "Quick capture: create issue and output only its ID.",
        subcommand: "q",
        outputKey: "result",
        params: [],
    },
    // --- Labels ---
    {
        name: "bd_label_add",
        description: "Add a label to one or more issues.",
        subcommand: "label add",
        outputKey: "result",
        params: [
            issueIds(),
            {
                name: "label",
                type: "string",
                description: "Label to add.",
                required: true,
                position: "trailing",
                quote: false,
            },
        ],
    },
    {
        name: "bd_label_remove",
        description: "Remove a label from one or more issues.",
        subcommand: "label remove",
        outputKey: "result",
        params: [
            issueIds(),
            {
                name: "label",
                type: "string",
                description: "Label to remove.",
                required: true,
                position: "trailing",
                quote: false,
            },
        ],
    },
    {
        name: "bd_label_list",
        description: "List labels for an issue.",
        subcommand: "label list",
        outputKey: "result",
        params: [
            {
                name: "issueId",
                type: "string",
                description: "Issue ID.",
                required: true,
                position: "trailing",
                quote: false,
            },
        ],
    },
    {
        name: "bd_label_list_all",
        description: "List all unique labels in the database.",
        subcommand: "label list-all",
        outputKey: "result",
        params: [],
    },
    // --- List & reports ---
    {
        name: "bd_list",
        description: "List issues matching filters. Use parent for children; tree/flat control hierarchy (bd 1.0+). Note: bd list has no --query flag; use beads_bd_search for text search.",
        subcommand: "list",
        outputKey: "issues",
        params: [
            ...listFilterParams,
            ...sortParams,
            {
                name: "format",
                type: "string",
                description: "Output format: digraph, dot, or Go template.",
                flag: "format",
            },
            {
                name: "long",
                type: "boolean",
                description: "Show detailed multi-line output.",
                flag: "long",
            },
            {
                name: "pretty",
                type: "boolean",
                description: "Display issues in tree format.",
                flag: "pretty",
            },
        ],
    },
    {
        name: "bd_count",
        description: "Count issues matching filters.",
        subcommand: "count",
        outputKey: "result",
        params: [
            ...listFilterParams.filter((p) =>
                ["assignee", "status", "type", "label", "labelAny", "priority", "priorityMin", "priorityMax", "title", "id"].includes(p.name),
            ),
            {
                name: "byStatus",
                type: "boolean",
                description: "Group count by status.",
                flag: "by-status",
            },
            {
                name: "byPriority",
                type: "boolean",
                description: "Group count by priority.",
                flag: "by-priority",
            },
            {
                name: "byType",
                type: "boolean",
                description: "Group count by issue type.",
                flag: "by-type",
            },
            {
                name: "byAssignee",
                type: "boolean",
                description: "Group count by assignee.",
                flag: "by-assignee",
            },
            {
                name: "byLabel",
                type: "boolean",
                description: "Group count by label.",
                flag: "by-label",
            },
        ],
    },
    {
        name: "bd_stale",
        description: "Show stale issues (not updated recently).",
        subcommand: "stale",
        outputKey: "result",
        params: [],
    },
    {
        name: "bd_status",
        description: "Show issue database overview and statistics.",
        subcommand: "status",
        outputKey: "result",
        params: [
            {
                name: "assigned",
                type: "boolean",
                description: "Show issues assigned to current user.",
                flag: "assigned",
            },
            {
                name: "noActivity",
                type: "boolean",
                description: "Skip git activity tracking.",
                flag: "no-activity",
            },
        ],
    },
    {
        name: "bd_activity",
        description: "Show real-time molecule state feed.",
        subcommand: "activity",
        outputKey: "result",
        params: [
            {
                name: "follow",
                type: "boolean",
                description: "Real-time streaming.",
                flag: "follow",
            },
            {
                name: "limit",
                type: "number",
                description: "Maximum events to show.",
                flag: "limit",
            },
        ],
    },
    {
        name: "bd_ready",
        description: "Show ready work (no blockers, open or in_progress).",
        subcommand: "ready",
        outputKey: "result",
        params: [
            {
                name: "assignee",
                type: "string",
                description: "Filter by assignee.",
                shortFlag: "a",
            },
            {
                name: "parent",
                type: "string",
                description: "Filter to descendants of this bead/epic.",
                flag: "parent",
            },
            {
                name: "type",
                type: "string",
                description: "Filter by issue type.",
                shortFlag: "t",
            },
            {
                name: "limit",
                type: "number",
                description: "Maximum issues to show.",
                shortFlag: "n",
            },
        ],
    },
    {
        name: "bd_blocked",
        description: "Show blocked issues.",
        subcommand: "blocked",
        outputKey: "result",
        params: [],
    },
    {
        name: "bd_orphans",
        description: "Identify orphaned issues referenced in commits but still open.",
        subcommand: "orphans",
        outputKey: "result",
        params: [],
    },
    // --- Dependencies & structure ---
    {
        name: "bd_dep_add",
        description: "Add a dependency between two issues. Use --type parent-child for parent/child links.",
        subcommand: "dep add",
        outputKey: "result",
        params: [
            {
                name: "issueId",
                type: "string",
                description: "Issue ID.",
                required: true,
                position: "leading",
                quote: false,
            },
            {
                name: "dependsOnId",
                type: "string",
                description: "Depends-on issue ID (or external:project:capability).",
                required: true,
                position: "leading",
                quote: false,
            },
            {
                name: "type",
                type: "string",
                description: "Dependency type (blocks, parent-child, discovered-from, etc.).",
                shortFlag: "t",
            },
        ],
    },
    {
        name: "bd_dep_remove",
        description: "Remove a dependency between two issues.",
        subcommand: "dep remove",
        outputKey: "result",
        params: [
            {
                name: "issueId",
                type: "string",
                description: "Issue ID.",
                required: true,
                position: "leading",
                quote: false,
            },
            {
                name: "dependsOnId",
                type: "string",
                description: "Depends-on issue ID to remove.",
                required: true,
                position: "leading",
                quote: false,
            },
        ],
    },
    {
        name: "bd_dep_list",
        description: "List dependencies or: bd dep list <issue-id> [--direction down|up|both].",
        subcommand: "dep list",
        outputKey: "result",
        params: [
            {
                name: "issueId",
                type: "string",
                description: "Issue ID.",
                required: true,
                position: "leading",
                quote: false,
            },
            {
                name: "direction",
                type: "string",
                description: "Direction: down (dependents), up (dependencies), or both.",
                flag: "direction",
            },
        ],
    },
    {
        name: "bd_dep_relate",
        description: "Create a bidirectional relates_to link between issues.",
        subcommand: "dep relate",
        outputKey: "result",
        params: [
            {
                name: "issueId1",
                type: "string",
                description: "First issue ID.",
                required: true,
                position: "leading",
                quote: false,
            },
            {
                name: "issueId2",
                type: "string",
                description: "Second issue ID.",
                required: true,
                position: "leading",
                quote: false,
            },
        ],
    },
    {
        name: "bd_dep_tree",
        description: "Show dependency tree for an issue.",
        subcommand: "dep tree",
        outputKey: "result",
        params: [
            {
                name: "issueId",
                type: "string",
                description: "Issue ID.",
                required: true,
                position: "trailing",
                quote: false,
            },
        ],
    },
    {
        name: "bd_dep_cycles",
        description: "Detect dependency cycles.",
        subcommand: "dep cycles",
        outputKey: "result",
        params: [],
    },
    {
        name: "bd_duplicate",
        description: "Mark an issue as a duplicate of a canonical issue.",
        subcommand: "duplicate",
        outputKey: "result",
        params: [
            {
                name: "issueId",
                type: "string",
                description: "Duplicate issue ID.",
                required: true,
                position: "leading",
                quote: false,
            },
            {
                name: "of",
                type: "string",
                description: "Canonical issue ID.",
                required: true,
                flag: "of",
            },
        ],
    },
    {
        name: "bd_duplicates",
        description: "Find issues with identical content.",
        subcommand: "duplicates",
        outputKey: "result",
        params: [
            {
                name: "autoMerge",
                type: "boolean",
                description: "Automatically merge all duplicates.",
                flag: "auto-merge",
            },
            {
                name: "dryRun",
                type: "boolean",
                description: "Show what would be merged without making changes.",
                flag: "dry-run",
            },
        ],
    },
    passthrough("bd_epic", "epic", "Epic management commands."),
    {
        name: "bd_graph",
        description: "Display ASCII dependency graph for an issue.",
        subcommand: "graph",
        outputKey: "result",
        params: [
            {
                name: "issueId",
                type: "string",
                description: "Issue ID.",
                required: true,
                position: "trailing",
                quote: false,
            },
        ],
    },
    {
        name: "bd_supersede",
        description: "Mark an issue as superseded by a newer version.",
        subcommand: "supersede",
        outputKey: "result",
        params: [
            {
                name: "issueId",
                type: "string",
                description: "Superseded issue ID.",
                required: true,
                position: "leading",
                quote: false,
            },
            {
                name: "with",
                type: "string",
                description: "Replacement issue ID.",
                required: true,
                flag: "with",
            },
        ],
    },
    passthrough("bd_swarm", "swarm", "Swarm management for structured epics."),
  // --- Sync & data ---
    {
        name: "bd_export",
        description: "Export issues to JSONL format.",
        subcommand: "export",
        outputKey: "result",
        params: [
            {
                name: "output",
                type: "string",
                description: "Output file (default: stdout).",
                shortFlag: "o",
                quote: true,
            },
            {
                name: "status",
                type: "string",
                description: "Filter by status.",
                shortFlag: "s",
            },
            {
                name: "type",
                type: "string",
                description: "Filter by type.",
                shortFlag: "t",
            },
        ],
    },
    {
        name: "bd_import",
        description: "Import issues from JSONL format.",
        subcommand: "import",
        outputKey: "result",
        params: [
            {
                name: "input",
                type: "string",
                description: "Input file (default: stdin).",
                shortFlag: "i",
                quote: true,
            },
            {
                name: "dryRun",
                type: "boolean",
                description: "Preview without making changes.",
                flag: "dry-run",
            },
            {
                name: "skipExisting",
                type: "boolean",
                description: "Skip existing issues instead of updating.",
                shortFlag: "s",
            },
        ],
    },
    {
        name: "bd_sync",
        description: "Synchronize issues with git remote.",
        subcommand: "sync",
        outputKey: "result",
        params: [
            {
                name: "noPull",
                type: "boolean",
                description: "Skip pulling from remote.",
                flag: "no-pull",
            },
            {
                name: "noPush",
                type: "boolean",
                description: "Skip pushing to remote.",
                flag: "no-push",
            },
            {
                name: "status",
                type: "boolean",
                description: "Show diff between sync branch and main.",
                flag: "status",
            },
        ],
    },
    passthrough("bd_restore", "restore", "Restore full history of a compacted issue from git."),
    passthrough("bd_merge", "merge", "Git merge driver for beads JSONL files."),
    passthrough("bd_daemon", "daemon", "Manage background sync daemon."),
    // --- Setup & config ---
    {
        name: "bd_config_get",
        description: "Get a configuration value.",
        subcommand: "config get",
        outputKey: "result",
        params: [
            {
                name: "key",
                type: "string",
                description: "Configuration key.",
                required: true,
                position: "trailing",
                quote: false,
            },
        ],
    },
    {
        name: "bd_config_set",
        description: "Set a configuration value.",
        subcommand: "config set",
        outputKey: "result",
        params: [
            {
                name: "key",
                type: "string",
                description: "Configuration key.",
                required: true,
                position: "leading",
                quote: false,
            },
            {
                name: "value",
                type: "string",
                description: "Configuration value.",
                required: true,
                position: "trailing",
                quote: true,
            },
        ],
    },
  {
        name: "bd_config_list",
        description: "List all configuration.",
        subcommand: "config list",
        outputKey: "result",
        params: [],
    },
    {
        name: "bd_config_unset",
        description: "Delete a configuration value.",
        subcommand: "config unset",
        outputKey: "result",
        params: [
            {
                name: "key",
                type: "string",
                description: "Configuration key.",
                required: true,
                position: "trailing",
                quote: false,
            },
        ],
    },
    passthrough("bd_hooks", "hooks", "Manage git hooks for bd auto-sync."),
    {
        name: "bd_human",
        description: "Show essential commands for human users.",
        subcommand: "human",
        outputKey: "result",
        params: [],
    },
    {
        name: "bd_info",
        description: "Show database and daemon information.",
        subcommand: "info",
        outputKey: "result",
        params: [],
    },
    {
        name: "bd_init",
        description: "Initialize bd in the current directory.",
        subcommand: "init",
        outputKey: "result",
        params: [
            {
                name: "prefix",
                type: "string",
                description: "Issue prefix.",
                shortFlag: "p",
            },
            {
                name: "force",
                type: "boolean",
                description: "Force re-initialization.",
                flag: "force",
            },
            {
                name: "fromJsonl",
                type: "boolean",
                description: "Import from current .beads/issues.jsonl.",
                flag: "from-jsonl",
            },
        ],
        includeGlobalFlags: false,
    },
    {
        name: "bd_onboard",
        description: "Display minimal snippet for AGENTS.md.",
        subcommand: "onboard",
        outputKey: "result",
        params: [],
    },
    {
        name: "bd_prime",
        description: "Output AI-optimized workflow context.",
        subcommand: "prime",
        outputKey: "result",
        params: [],
    },
    {
        name: "bd_quickstart",
        description: "Quick start guide for bd.",
        subcommand: "quickstart",
        outputKey: "result",
        params: [],
    },
    {
        name: "bd_setup",
        description: "Setup integration with AI editors.",
        subcommand: "setup",
        outputKey: "result",
        params: [],
    },
    {
        name: "bd_where",
        description: "Show active beads location.",
        subcommand: "where",
        outputKey: "result",
        params: [],
    },
    // --- Maintenance ---
    {
        name: "bd_doctor",
        description: "Check and fix beads installation health.",
        subcommand: "doctor",
        outputKey: "result",
        params: [
            {
                name: "fix",
                type: "boolean",
                description: "Attempt to fix issues.",
                flag: "fix",
            },
        ],
    },
    passthrough("bd_migrate", "migrate", "Database migration commands."),
    {
        name: "bd_preflight",
        description: "Show PR readiness checklist.",
        subcommand: "preflight",
        outputKey: "result",
        params: [],
    },
    {
        name: "bd_repair",
        description: "Repair corrupted database by cleaning orphaned references.",
        subcommand: "repair",
        outputKey: "result",
        params: [],
    },
    {
        name: "bd_rename_prefix",
        description: "Rename the issue prefix for all issues.",
        subcommand: "rename-prefix",
        outputKey: "result",
        params: [
            {
                name: "newPrefix",
                type: "string",
                description: "New issue prefix.",
                required: true,
                position: "trailing",
                quote: false,
            },
        ],
    },
    {
        name: "bd_upgrade",
        description: "Check and manage bd version upgrades.",
        subcommand: "upgrade",
        outputKey: "result",
        params: [
            {
                name: "check",
                type: "boolean",
                description: "Check for available upgrades.",
                flag: "check",
            },
        ],
    },
    passthrough("bd_worktree", "worktree", "Manage git worktrees for parallel development."),
    passthrough("bd_admin", "admin", "Administrative commands for database maintenance."),
    // --- Integrations ---
    passthrough("bd_jira", "jira", "Jira integration commands."),
    passthrough("bd_linear", "linear", "Linear integration commands."),
    passthrough("bd_repo", "repo", "Manage multiple repository configuration."),
    {
        name: "bd_audit",
        description: "Record and label agent interactions.",
        subcommand: "audit",
        outputKey: "result",
        params: [
            {
                name: "record",
                type: "string",
                description: "Record an audit event.",
                flag: "record",
                quote: true,
            },
        ],
    },
    {
        name: "bd_completion",
        description: "Generate shell autocompletion script.",
        subcommand: "completion",
        outputKey: "result",
        params: [
            {
                name: "shell",
                type: "string",
                description: "Shell name (bash, zsh, fish).",
                required: true,
                position: "trailing",
                quote: false,
            },
        ],
    },
    {
        name: "bd_cook",
        description: "Compile a formula into a proto.",
        subcommand: "cook",
        outputKey: "result",
        params: [
            {
                name: "formula",
                type: "string",
                description: "Formula name.",
                required: true,
                position: "trailing",
                quote: true,
            },
            {
                name: "ephemeral",
                type: "boolean",
                description: "Create as ephemeral proto.",
                flag: "ephemeral",
            },
        ],
    },
    passthrough("bd_formula", "formula", "Manage workflow formulas."),
    {
        name: "bd_help",
        description: "Help about bd commands.",
        subcommand: "help",
        outputKey: "result",
        params: [
            {
                name: "command",
                type: "string",
                description: "Command to get help for.",
                position: "trailing",
                quote: false,
            },
        ],
    },
    passthrough("bd_mail", "mail", "Delegate to mail provider."),
    passthrough("bd_mol", "mol", "Molecule commands (work templates)."),
    passthrough("bd_gate", "gate", "Gate commands (async coordination)."),
    passthrough("bd_slot", "slot", "Manage agent bead slots."),
    passthrough("bd_agent", "agent", "Manage agent bead state."),
    {
        name: "bd_ship",
        description: "Publish a capability for cross-project dependencies.",
        subcommand: "ship",
        outputKey: "result",
        params: [
            {
                name: "capability",
                type: "string",
                description: "Capability name.",
                required: true,
                position: "trailing",
                quote: false,
            },
            {
                name: "force",
                type: "boolean",
                description: "Ship even if issue is not closed.",
                flag: "force",
            },
            {
                name: "dryRun",
                type: "boolean",
                description: "Preview without making changes.",
                flag: "dry-run",
            },
        ],
    },
];

export const EXPECTED_TOOL_NAMES = BD_TOOL_SPECS.map((spec) => spec.name);

export const BD_TOOL_TEST_CASES: ToolTestCase[] = [
    { tool: "bd_version", command: "--version" },
    {
        tool: "bd_close",
        args: { issueIds: ["dotfiles-1", "dotfiles-2"] },
        command: "close dotfiles-1 dotfiles-2",
    },
    {
        tool: "bd_comment",
        args: { issueId: "dotfiles-1", text: "Looks good" },
        command: 'comment dotfiles-1 "Looks good"',
    },
    {
        tool: "bd_comments",
        args: { issueId: "dotfiles-1" },
        command: "comments dotfiles-1",
    },
    {
        tool: "bd_comments_add",
        args: { issueId: "dotfiles-1", text: "Update" },
        command: 'comments add dotfiles-1 "Update"',
    },
    {
        tool: "bd_create",
        args: { title: "Task", type: "task", description: "Do it" },
        command: 'create --title "Task" -t task -d "Do it"',
    },
    {
        tool: "bd_create",
        args: { parent: "dotfiles-5a3", title: "Child task", type: "task" },
        command: 'create --title "Child task" -t task --parent dotfiles-5a3',
    },
    { tool: "bd_create_form", command: "create-form" },
    {
        tool: "bd_delete",
        args: { issueIds: ["dotfiles-1"] },
        command: "delete dotfiles-1",
    },
    {
        tool: "bd_edit",
        args: { issueId: "dotfiles-1", title: true },
        command: "edit dotfiles-1 --title",
    },
    {
        tool: "bd_update",
        args: { issueIds: ["dotfiles-1"], title: "New title", status: "in_progress" },
        command: 'update dotfiles-1 --title "New title" -s in_progress',
    },
    {
        tool: "bd_update",
        args: { issueIds: ["dotfiles-70e"], parent: "dotfiles-5a3" },
        command: "update dotfiles-70e --parent dotfiles-5a3",
    },
    {
        tool: "bd_defer",
        args: { issueIds: ["dotfiles-1"] },
        command: "defer dotfiles-1",
    },
    {
        tool: "bd_undefer",
        args: { issueIds: ["dotfiles-1"] },
        command: "undefer dotfiles-1",
    },
    {
        tool: "bd_reopen",
        args: { issueIds: ["dotfiles-1"] },
        command: "reopen dotfiles-1",
    },
    {
        tool: "bd_search",
        args: { query: "login bug", status: "open" },
        command: 'search "login bug" -s open',
    },
    {
        tool: "bd_set_state",
        args: { issueId: "dotfiles-1", state: "patrol=muted", reason: "Paused" },
        command: 'set-state dotfiles-1 patrol=muted --reason "Paused"',
    },
    {
        tool: "bd_show",
        args: { issueIds: ["dotfiles-1"] },
        command: "show dotfiles-1",
    },
    { tool: "bd_q", command: "q" },
    {
        tool: "bd_label_add",
        args: { issueIds: ["dotfiles-1"], label: "bug" },
        command: "label add dotfiles-1 bug",
    },
    {
        tool: "bd_label_remove",
        args: { issueIds: ["dotfiles-1"], label: "bug" },
        command: "label remove dotfiles-1 bug",
    },
    {
        tool: "bd_label_list",
        args: { issueId: "dotfiles-1" },
        command: "label list dotfiles-1",
    },
    { tool: "bd_label_list_all", command: "label list-all" },
    {
        tool: "bd_list",
        args: { parent: "dotfiles-5a3" },
        command: "list --parent dotfiles-5a3",
    },
    {
        tool: "bd_list",
        args: { status: "open", limit: 10 },
        command: "list -s open -n 10",
    },
    {
        tool: "bd_count",
        args: { status: "open", byStatus: true },
        command: "count -s open --by-status",
    },
    { tool: "bd_stale", command: "stale" },
    { tool: "bd_status", command: "status" },
    { tool: "bd_activity", command: "activity" },
    {
        tool: "bd_ready",
        args: { assignee: "alice", parent: "dotfiles-5a3" },
        command: "ready -a alice --parent dotfiles-5a3",
    },
    { tool: "bd_blocked", command: "blocked" },
    { tool: "bd_orphans", command: "orphans" },
    {
        tool: "bd_link",
        args: { issueId1: "dotfiles-70e", issueId2: "dotfiles-5a3", type: "parent-child" },
        command: "link dotfiles-70e dotfiles-5a3 -t parent-child",
    },
    {
        tool: "bd_batch",
        args: { file: "/tmp/bd-batch.txt", dryRun: true },
        command: 'batch -f "/tmp/bd-batch.txt" --dry-run',
    },
    {
        tool: "bd_create",
        args: { graph: "issues.graph.json" },
        command: 'create --graph "issues.graph.json"',
    },
    {
        tool: "bd_dep_add",
        args: { issueId: "dotfiles-70e", dependsOnId: "dotfiles-5a3", type: "parent-child" },
        command: "dep add dotfiles-70e dotfiles-5a3 -t parent-child",
    },
    {
        tool: "bd_dep_remove",
        args: { issueId: "dotfiles-70e", dependsOnId: "dotfiles-5a3" },
        command: "dep remove dotfiles-70e dotfiles-5a3",
    },
    {
        tool: "bd_dep_list",
        args: { issueId: "dotfiles-5a3", direction: "down" },
        command: "dep list dotfiles-5a3 --direction down",
    },
    {
        tool: "bd_dep_relate",
        args: { issueId1: "dotfiles-1", issueId2: "dotfiles-2" },
        command: "dep relate dotfiles-1 dotfiles-2",
    },
    {
        tool: "bd_dep_tree",
        args: { issueId: "dotfiles-5a3" },
        command: "dep tree dotfiles-5a3",
    },
    { tool: "bd_dep_cycles", command: "dep cycles" },
    {
        tool: "bd_duplicate",
        args: { issueId: "dotfiles-1", of: "dotfiles-2" },
        command: "duplicate dotfiles-1 --of dotfiles-2",
    },
    {
        tool: "bd_duplicates",
        args: { dryRun: true },
        command: "duplicates --dry-run",
    },
    {
        tool: "bd_epic",
        args: { command: "status dotfiles-5a3" },
        command: "epic status dotfiles-5a3",
    },
    {
        tool: "bd_graph",
        args: { issueId: "dotfiles-5a3" },
        command: "graph dotfiles-5a3",
    },
    {
        tool: "bd_supersede",
        args: { issueId: "dotfiles-1", with: "dotfiles-2" },
        command: "supersede dotfiles-1 --with dotfiles-2",
    },
    {
        tool: "bd_swarm",
        args: { command: "list" },
        command: "swarm list",
    },
    {
        tool: "bd_export",
        args: { status: "open", output: "open.jsonl" },
        command: 'export -o "open.jsonl" -s open',
    },
    {
        tool: "bd_import",
        args: { input: "issues.jsonl", dryRun: true },
        command: 'import -i "issues.jsonl" --dry-run',
    },
    {
        tool: "bd_sync",
        args: { noPush: true },
        command: "sync --no-push",
    },
    {
        tool: "bd_config_get",
        args: { key: "issue.prefix" },
        command: "config get issue.prefix",
    },
    {
        tool: "bd_config_set",
        args: { key: "issue.prefix", value: "dotfiles" },
        command: 'config set issue.prefix "dotfiles"',
    },
    { tool: "bd_config_list", command: "config list" },
    {
        tool: "bd_config_unset",
        args: { key: "issue.prefix" },
        command: "config unset issue.prefix",
    },
    { tool: "bd_human", command: "human" },
    { tool: "bd_info", command: "info" },
    {
        tool: "bd_init",
        args: { prefix: "dotfiles" },
        command: "init -p dotfiles",
    },
    { tool: "bd_onboard", command: "onboard" },
    { tool: "bd_prime", command: "prime" },
    { tool: "bd_quickstart", command: "quickstart" },
    { tool: "bd_where", command: "where" },
    { tool: "bd_doctor", args: { fix: true }, command: "doctor --fix" },
    { tool: "bd_preflight", command: "preflight" },
    { tool: "bd_repair", command: "repair" },
    {
        tool: "bd_rename_prefix",
        args: { newPrefix: "dotfiles" },
        command: "rename-prefix dotfiles",
    },
    {
        tool: "bd_upgrade",
        args: { check: true },
        command: "upgrade --check",
    },
    {
        tool: "bd_admin",
        args: { command: "compact --dry-run" },
        command: "admin compact --dry-run",
    },
    {
        tool: "bd_repo",
        args: { command: "list" },
        command: "repo list",
    },
    {
        tool: "bd_audit",
        args: { record: "session-start" },
        command: 'audit --record "session-start"',
    },
    {
        tool: "bd_completion",
        args: { shell: "bash" },
        command: "completion bash",
    },
    {
        tool: "bd_cook",
        args: { formula: "deploy", ephemeral: true },
        command: 'cook "deploy" --ephemeral',
    },
    {
        tool: "bd_help",
        args: { command: "create" },
        command: "help create",
    },
    {
        tool: "bd_ship",
        args: { capability: "auth", dryRun: true },
        command: "ship auth --dry-run",
    },
    {
        tool: "bd_gate",
        args: { command: "list" },
        command: "gate list",
    },
];

export function getToolSpec(name: string): BdToolSpec {
    const spec = BD_TOOL_SPECS.find((entry) => entry.name === name);
    if (!spec) {
        throw new Error(`Unknown tool spec: ${name}`);
    }
    return spec;
}
