# Colocated suite for rust/tools/oomkiller/Cargo.nix.
# This file is @generated by crate2nix — regenerate, never hand-edit.
# Guard scope: the artifact parses, applies, and exposes its stable public API.
let
  assay = import ./../../../common/assay/default.nix;
  # Explicit stubs avoid touching <nixpkgs>; generated header stays lazy.
  generated = import ./Cargo.nix {
    pkgs = {};
    lib = {};
    stdenv = {};
    buildRustCrateForPkgs = _: {};
    defaultCrateOverrides = {};
  };
  names = builtins.attrNames generated;
  has = n: builtins.elem n names;
in
  assay.suite "oomkiller-cargo-nix" {
    evaluatesToAttrset = assay.eq (builtins.isAttrs generated) true;
    exposesRootCrate = assay.eq (has "rootCrate") true;
    exposesWorkspaceMembers = assay.eq (has "workspaceMembers") true;
    rootCrateIsOomkiller = assay.eq
      (generated.rootCrate.packageId or "")
      "oomkiller";
    singleWorkspaceMember = assay.eq
      (builtins.attrNames generated.workspaceMembers)
      ["oomkiller"];
  }
