Guidelime.registerGuide(
[[
[GA Alliance]
[N14-17 Loch Modan]
[NX17-19 Darkshore]
[D This guide was written by TUGs and is totally free, but if you want to support my work use: https://www.youtube.com/user/HydroxXTV]
This guide was written by TUGs and is totally free, but if you want to support my work use: https://www.youtube.com/user/HydroxXTV
[T] Get your Level 14 skills at your trainer.
Accept: [QA2999][A Paladin]
TurnIn: [QT2999]
[A Paladin]You just got a QuestItem Tome of Divinity. Accept the Quest.
Accept: [QA1646][A Paladin]
TurnIn: [QT1646][A Paladin]
Accept: [QA1647][A Paladin]
TurnIn: [QT1647][A Paladin]
Accept: [QA1648][A Paladin]
[A Paladin]If you dont have 10 Linen Cloth, just buy it from the auction house, its always cheap.
TurnIn: [QT1648][A Paladin]
Accept: [QA1778][A Paladin]
TurnIn: [QT1778][A Paladin]
Accept: [QA1779][A Paladin]
TurnIn: [QT1779][A Paladin]
Accept: [QA1783][A Paladin]
Accept: [QA2039]
Accept: [QA6392][A Dwarf, Gnome]
Fly to [F Loch Modan]
Accept: [QA436]
TurnIn: [QT6392][A Dwarf, Gnome]
Accept: [QA224][A Nightelf]
Accept: [QA267][A Nightelf]
Do: [QC224][A Nightelf]
TurnIn: [QT224][A Nightelf]
Accept: [QA237]
Do: [QC237]
Do: [QC267][A Nightelf]
TurnIn: [QT237]
TurnIn: [QT267][A Nightelf]
Accept: [QA263]
Do: [QC1783][A Paladin]
TurnIn: [QT436]
Accept: [QA297]
Accept: [QA298]
Accept: [QA257]
Do: [QC257]
TurnIn: [QT257]
Accept: [QA258]
Do: [QC258]
TurnIn: [QT258]
Accept: [QA271][O]
Accept: [QA385]
TurnIn: [QT2039]
Accept: [QA2038]
Do: [QC385]
Do: [QC2038]
Do: [QC263]
Accept: [QA250]
TurnIn: [QT250]
Accept: [QA199]
TurnIn: [QT199]
TurnIn: [QT2038]
TurnIn: [QT385]
Do: [QC297]
Grind the troggs till level [XP17+500 17+500]
TurnIn: [QT297]
Die on purpose and rezz up.
TurnIn: [QT298]
Accept: [QA301]
TurnIn: [QT263]
Use your [H] Hearthstone.
[T] Get your Level 16 skills at your trainer.
TurnIn: [QT301]
Fly to [F Wetlands]
Take the boat to Darkshore
Thanks for using my guide. If it helped you and you "want to give back a little": There is a Paypal-Link on curseforge. Thanks <3
]], "TUGs The Ultimate (Leveling) Guides")