Guidelime.registerGuide(
[[
[GA Alliance]
[N19-21 Redridge Mountains]
[NX21-22 Ashenvale]
[D This guide was written by TUGs and is totally free, but if you want to support my work use: https://www.youtube.com/user/HydroxXTV]
This guide was written by TUGs and is totally free, but if you want to support my work use: https://www.youtube.com/user/HydroxXTV
TurnIn: [QT1338]
Accept: [QA3765]
Set your [S] to Stormwind City at [G52.6, 65.7Stormwind City]
Get the [P] flightpath at: [G66.2, 62.4Stormwind City][A Nightelf,Gnome,Dwarf]
Fly to [F Redridge Mountains][A Human]
Accept: [QA244]
TurnIn: [QT244]
Accept: [QA246]
Get the [P] flightpath at: [G30.6,59.4Redridge Mountains][A Nightelf,Gnome,Dwarf]
Accept: [QA20]
Accept: [QA125]
Accept: [QA118]
Accept: [QA120]
Accept: [QA3741]
Accept: [QA129]
Do: [QC3741]
Kill as many Mongrels as you can at [G17,65]
TurnIn: [QT129]
Accept: [QA130]
Do: [QC246]
Do: [QC125]
Run to [G70.6, 79.1Redridge Mountains]
Do: [QC20]
Grind the Orcs till level [XP20 20]
Use your [H] Hearthstone.
TurnIn: [QT118]
Accept: [QA119]
TurnIn: [QT120]
Accept: [QA121]
[T] Get your Level 20 skills at your trainer.
Accept: [QA1698][A Warrior]
Fly to [F Redridge Mountains]
TurnIn: [QT246]
TurnIn: [QT20]
TurnIn: [QT125]
Accept: [QA89]
TurnIn: [QT119]
Accept: [QA124]
TurnIn: [QT3741]
TurnIn: [QT121]
TurnIn: [QT130]
Accept: [QA131]
TurnIn: [QT131]
Set your [S] to Redridge Mountains at [G26.8,44.6Redridge Mountains]
TurnIn: [QT1698]
Do [QC124- ][QC89 A Baying of Gnolls,The Everstill Bridge]
TurnIn: [QT124]
TurnIn: [QT89]
Grind  the gnolls till level [XP20+19800 20+19800]
Fly to [F Wetlands]
TurnIn: [QT942]
Take the boat to Auberdine.
Thanks for using my guide. If it helped you and you "want to give back a little": There is a Paypal-Link on curseforge. Thanks <3
]], "TUGs The Ultimate (Leveling) Guides")