# This file was @generated by crate2nix 0.15.0 with the command:
#   "generate" "-f" "/home/tom/.dotfiles/rust/tools/ls/Cargo.toml" "-o" "/home/tom/.dotfiles/rust/tools/ls/Cargo.nix"
# See https://github.com/kolloch/crate2nix for more info.
{
  nixpkgs ? <nixpkgs>,
  pkgs ? import nixpkgs {config = {};},
  fetchurl ? pkgs.fetchurl,
  lib ? pkgs.lib,
  stdenv ? pkgs.stdenv,
  buildRustCrateForPkgs ? pkgs: pkgs.buildRustCrate,
  # This is used as the `crateOverrides` argument for `buildRustCrate`.
  defaultCrateOverrides ? pkgs.defaultCrateOverrides,
  # The features to enable for the root_crate or the workspace_members.
  rootFeatures ? ["default"],
  # If true, throw errors instead of issueing deprecation warnings.
  strictDeprecation ? false,
  # Elements to add to the `-C target-feature=` argument passed to `rustc`
  # (separated by `,`, prefixed with `+`).
  # Used for conditional compilation based on CPU feature detection.
  targetFeatures ? [],
  # Additional target attributes for conditional dependencies.
  # Use this for custom cfg flags that are passed via rustcflags but need to
  # be known at Nix evaluation time for dependency resolution.
  # Example: { tracing_unstable = true; } for crates using cfg(tracing_unstable).
  extraTargetFlags ? {},
  # Whether to perform release builds: longer compile times, faster binaries.
  release ? true,
  # Additional crate2nix configuration if it exists.
  crateConfig ?
    if builtins.pathExists ./crate-config.nix
    then pkgs.callPackage ./crate-config.nix {}
    else {},
}: rec {
  #
  # "public" attributes that we attempt to keep stable with new versions of crate2nix.
  #

  rootCrate = rec {
    packageId = "ls";

    # Use this attribute to refer to the derivation building your root crate package.
    # You can override the features with rootCrate.build.override { features = [ "default" "feature1" ... ]; }.
    build = internal.buildRustCrateWithFeatures {
      inherit packageId;
    };

    # Debug support which might change between releases.
    # File a bug if you depend on any for non-debug work!
    debug = internal.debugCrate {inherit packageId;};
  };
  # Refer your crate build derivation by name here.
  # You can override the features with
  # workspaceMembers."${crateName}".build.override { features = [ "default" "feature1" ... ]; }.
  workspaceMembers = {
    "ls" = rec {
      packageId = "ls";
      build = internal.buildRustCrateWithFeatures {
        packageId = "ls";
      };

      # Debug support which might change between releases.
      # File a bug if you depend on any for non-debug work!
      debug = internal.debugCrate {inherit packageId;};
    };
  };

  # A derivation that joins the outputs of all workspace members together.
  allWorkspaceMembers = pkgs.symlinkJoin {
    name = "all-workspace-members";
    paths = let
      members = builtins.attrValues workspaceMembers;
    in
      builtins.map (m: m.build) members;
  };

  #
  # "internal" ("private") attributes that may change in every new version of crate2nix.
  #

  internal = rec {
    # Build and dependency information for crates.
    # Many of the fields are passed one-to-one to buildRustCrate.
    #
    # Noteworthy:
    # * `dependencies`/`buildDependencies`: similar to the corresponding fields for buildRustCrate.
    #   but with additional information which is used during dependency/feature resolution.
    # * `resolvedDependencies`: the selected default features reported by cargo - only included for debugging.
    # * `devDependencies` as of now not used by `buildRustCrate` but used to
    #   inject test dependencies into the build

    crates = {
      "bitmaps" = rec {
        crateName = "bitmaps";
        version = "2.1.0";
        edition = "2018";
        sha256 = "18k4mcwxl96yvii5kcljkpb8pg5j4jj1zbsdn26nsx4r83846403";
        authors = [
          "Bodil Stokke <bodil@bodil.org>"
        ];
        dependencies = [
          {
            name = "typenum";
            packageId = "typenum";
          }
        ];
        features = {
          "default" = ["std"];
        };
        resolvedDefaultFeatures = ["default" "std"];
      };
      "bumpalo" = rec {
        crateName = "bumpalo";
        version = "3.20.2";
        edition = "2021";
        sha256 = "1jrgxlff76k9glam0akhwpil2fr1w32gbjdf5hpipc7ld2c7h82x";
        authors = [
          "Nick Fitzgerald <fitzgen@gmail.com>"
        ];
        features = {
          "allocator-api2" = ["dep:allocator-api2"];
          "bench_allocator_api" = ["allocator_api" "blink-alloc/nightly"];
          "serde" = ["dep:serde"];
        };
        resolvedDefaultFeatures = ["default"];
      };
      "cfg-if" = rec {
        crateName = "cfg-if";
        version = "1.0.4";
        edition = "2018";
        sha256 = "008q28ajc546z5p2hcwdnckmg0hia7rnx52fni04bwqkzyrghc4k";
        libName = "cfg_if";
        authors = [
          "Alex Crichton <alex@alexcrichton.com>"
        ];
        features = {
          "core" = ["dep:core"];
          "rustc-dep-of-std" = ["core"];
        };
      };
      "fastrand" = rec {
        crateName = "fastrand";
        version = "2.4.1";
        edition = "2018";
        sha256 = "1mnqxxnxvd69ma9mczabpbbsgwlhd6l78yv3vd681453a9s247wz";
        authors = [
          "Stjepan Glavina <stjepang@gmail.com>"
        ];
        dependencies = [
          {
            name = "getrandom";
            packageId = "getrandom";
            optional = true;
            target = {
              target,
              features,
            }: ((("wasm32" == target."arch" or null) || ("wasm64" == target."arch" or null)) && ("unknown" == target."os" or null));
            features = ["wasm_js"];
          }
        ];
        devDependencies = [
          {
            name = "getrandom";
            packageId = "getrandom";
          }
          {
            name = "getrandom";
            packageId = "getrandom";
            target = {
              target,
              features,
            }: ((("wasm32" == target."arch" or null) || ("wasm64" == target."arch" or null)) && ("unknown" == target."os" or null));
            features = ["wasm_js"];
          }
        ];
        features = {
          "default" = ["std"];
          "getrandom" = ["dep:getrandom"];
          "js" = ["std" "getrandom"];
          "std" = ["alloc"];
        };
        resolvedDefaultFeatures = ["alloc" "default" "getrandom" "js" "std"];
      };
      "flume" = rec {
        crateName = "flume";
        version = "0.12.0";
        edition = "2018";
        sha256 = "1gnk7gji9r12ig35czj2cq441zf5ijmz0bgnz9gfnxx7dk29n4sy";
        authors = [
          "Joshua Barretto <joshua.s.barretto@gmail.com>"
        ];
        dependencies = [
          {
            name = "fastrand";
            packageId = "fastrand";
            optional = true;
            features = ["std" "js"];
          }
          {
            name = "futures-core";
            packageId = "futures-core";
            optional = true;
            usesDefaultFeatures = false;
          }
          {
            name = "futures-sink";
            packageId = "futures-sink";
            optional = true;
            usesDefaultFeatures = false;
          }
          {
            name = "spin";
            packageId = "spin";
            rename = "spin1";
            features = ["mutex"];
          }
        ];
        features = {
          "async" = ["futures-sink" "futures-core"];
          "default" = ["async" "select" "eventual-fairness"];
          "eventual-fairness" = ["select" "fastrand"];
          "fastrand" = ["dep:fastrand"];
          "futures-core" = ["dep:futures-core"];
          "futures-sink" = ["dep:futures-sink"];
        };
        resolvedDefaultFeatures = ["async" "default" "eventual-fairness" "fastrand" "futures-core" "futures-sink" "select"];
      };
      "futures" = rec {
        crateName = "futures";
        version = "0.3.32";
        edition = "2018";
        sha256 = "0b9q86r5ar18v5xjiyqn7sb8sa32xv98qqnfz779gl7ns7lpw54b";
        dependencies = [
          {
            name = "futures-channel";
            packageId = "futures-channel";
            usesDefaultFeatures = false;
            features = ["sink"];
          }
          {
            name = "futures-core";
            packageId = "futures-core";
            usesDefaultFeatures = false;
          }
          {
            name = "futures-io";
            packageId = "futures-io";
            usesDefaultFeatures = false;
          }
          {
            name = "futures-sink";
            packageId = "futures-sink";
            usesDefaultFeatures = false;
          }
          {
            name = "futures-task";
            packageId = "futures-task";
            usesDefaultFeatures = false;
          }
          {
            name = "futures-util";
            packageId = "futures-util";
            usesDefaultFeatures = false;
            features = ["sink"];
          }
        ];
        features = {
          "alloc" = ["futures-core/alloc" "futures-task/alloc" "futures-sink/alloc" "futures-channel/alloc" "futures-util/alloc"];
          "async-await" = ["futures-util/async-await" "futures-util/async-await-macro"];
          "bilock" = ["futures-util/bilock"];
          "compat" = ["std" "futures-util/compat"];
          "default" = ["std" "async-await" "executor"];
          "executor" = ["std" "futures-executor/std"];
          "futures-executor" = ["dep:futures-executor"];
          "io-compat" = ["compat" "futures-util/io-compat"];
          "spin" = ["futures-util/spin"];
          "std" = ["alloc" "futures-core/std" "futures-task/std" "futures-io/std" "futures-sink/std" "futures-util/std" "futures-util/io" "futures-util/channel"];
          "thread-pool" = ["executor" "futures-executor/thread-pool"];
          "unstable" = ["futures-core/unstable" "futures-task/unstable" "futures-channel/unstable" "futures-io/unstable" "futures-util/unstable"];
          "write-all-vectored" = ["futures-util/write-all-vectored"];
        };
        resolvedDefaultFeatures = ["alloc" "std"];
      };
      "futures-channel" = rec {
        crateName = "futures-channel";
        version = "0.3.32";
        edition = "2018";
        sha256 = "07fcyzrmbmh7fh4ainilf1s7gnwvnk07phdq77jkb9fpa2ffifq7";
        libName = "futures_channel";
        dependencies = [
          {
            name = "futures-core";
            packageId = "futures-core";
            usesDefaultFeatures = false;
          }
          {
            name = "futures-sink";
            packageId = "futures-sink";
            optional = true;
            usesDefaultFeatures = false;
          }
        ];
        features = {
          "alloc" = ["futures-core/alloc"];
          "default" = ["std"];
          "futures-sink" = ["dep:futures-sink"];
          "sink" = ["futures-sink"];
          "std" = ["alloc" "futures-core/std"];
        };
        resolvedDefaultFeatures = ["alloc" "futures-sink" "sink" "std"];
      };
      "futures-core" = rec {
        crateName = "futures-core";
        version = "0.3.32";
        edition = "2018";
        sha256 = "07bbvwjbm5g2i330nyr1kcvjapkmdqzl4r6mqv75ivvjaa0m0d3y";
        libName = "futures_core";
        features = {
          "default" = ["std"];
          "portable-atomic" = ["dep:portable-atomic"];
          "std" = ["alloc"];
        };
        resolvedDefaultFeatures = ["alloc" "std"];
      };
      "futures-io" = rec {
        crateName = "futures-io";
        version = "0.3.32";
        edition = "2018";
        sha256 = "063pf5m6vfmyxj74447x8kx9q8zj6m9daamj4hvf49yrg9fs7jyf";
        libName = "futures_io";
        features = {
          "default" = ["std"];
        };
        resolvedDefaultFeatures = ["std"];
      };
      "futures-sink" = rec {
        crateName = "futures-sink";
        version = "0.3.32";
        edition = "2018";
        sha256 = "14q8ml7hn5a6gyy9ri236j28kh0svqmrk4gcg0wh26rkazhm95y3";
        libName = "futures_sink";
        features = {
          "default" = ["std"];
          "std" = ["alloc"];
        };
        resolvedDefaultFeatures = ["alloc" "std"];
      };
      "futures-task" = rec {
        crateName = "futures-task";
        version = "0.3.32";
        edition = "2018";
        sha256 = "14s3vqf8llz3kjza33vn4ixg6kwxp61xrysn716h0cwwsnri2xq3";
        libName = "futures_task";
        features = {
          "default" = ["std"];
          "std" = ["alloc"];
        };
        resolvedDefaultFeatures = ["alloc" "std"];
      };
      "futures-util" = rec {
        crateName = "futures-util";
        version = "0.3.32";
        edition = "2018";
        sha256 = "1mn60lw5kh32hz9isinjlpw34zx708fk5q1x0m40n6g6jq9a971q";
        libName = "futures_util";
        dependencies = [
          {
            name = "futures-channel";
            packageId = "futures-channel";
            optional = true;
            usesDefaultFeatures = false;
            features = ["std"];
          }
          {
            name = "futures-core";
            packageId = "futures-core";
            usesDefaultFeatures = false;
          }
          {
            name = "futures-io";
            packageId = "futures-io";
            optional = true;
            usesDefaultFeatures = false;
            features = ["std"];
          }
          {
            name = "futures-sink";
            packageId = "futures-sink";
            optional = true;
            usesDefaultFeatures = false;
          }
          {
            name = "futures-task";
            packageId = "futures-task";
            usesDefaultFeatures = false;
          }
          {
            name = "memchr";
            packageId = "memchr";
            optional = true;
          }
          {
            name = "pin-project-lite";
            packageId = "pin-project-lite";
          }
          {
            name = "slab";
            packageId = "slab";
            optional = true;
            usesDefaultFeatures = false;
          }
        ];
        features = {
          "alloc" = ["futures-core/alloc" "futures-task/alloc" "slab"];
          "async-await-macro" = ["async-await" "futures-macro"];
          "channel" = ["std" "futures-channel"];
          "compat" = ["std" "futures_01" "libc"];
          "default" = ["std" "async-await" "async-await-macro"];
          "futures-channel" = ["dep:futures-channel"];
          "futures-io" = ["dep:futures-io"];
          "futures-macro" = ["dep:futures-macro"];
          "futures-sink" = ["dep:futures-sink"];
          "futures_01" = ["dep:futures_01"];
          "io" = ["std" "futures-io" "memchr"];
          "io-compat" = ["io" "compat" "tokio-io" "libc"];
          "libc" = ["dep:libc"];
          "memchr" = ["dep:memchr"];
          "portable-atomic" = ["futures-core/portable-atomic"];
          "sink" = ["futures-sink"];
          "slab" = ["dep:slab"];
          "spin" = ["dep:spin"];
          "std" = ["alloc" "futures-core/std" "futures-task/std" "slab/std"];
          "tokio-io" = ["dep:tokio-io"];
          "unstable" = ["futures-core/unstable" "futures-task/unstable"];
          "write-all-vectored" = ["io"];
        };
        resolvedDefaultFeatures = ["alloc" "channel" "futures-channel" "futures-io" "futures-sink" "io" "memchr" "sink" "slab" "std"];
      };
      "getrandom" = rec {
        crateName = "getrandom";
        version = "0.3.4";
        edition = "2021";
        sha256 = "1zbpvpicry9lrbjmkd4msgj3ihff1q92i334chk7pzf46xffz7c9";
        authors = [
          "The Rand Project Developers"
        ];
        dependencies = [
          {
            name = "cfg-if";
            packageId = "cfg-if";
          }
          {
            name = "js-sys";
            packageId = "js-sys";
            optional = true;
            usesDefaultFeatures = false;
            target = {
              target,
              features,
            }: (("wasm32" == target."arch" or null) && (("unknown" == target."os" or null) || ("none" == target."os" or null)) && (builtins.elem "atomics" targetFeatures));
          }
          {
            name = "libc";
            packageId = "libc";
            usesDefaultFeatures = false;
            target = {
              target,
              features,
            }: ((("linux" == target."os" or null) || ("android" == target."os" or null)) && (!((("linux" == target."os" or null) && ("" == target."env" or null)) || ("custom" == target."getrandom_backend" or null) || ("linux_raw" == target."getrandom_backend" or null) || ("rdrand" == target."getrandom_backend" or null) || ("rndr" == target."getrandom_backend" or null))));
          }
          {
            name = "libc";
            packageId = "libc";
            usesDefaultFeatures = false;
            target = {
              target,
              features,
            }: (("dragonfly" == target."os" or null) || ("freebsd" == target."os" or null) || ("hurd" == target."os" or null) || ("illumos" == target."os" or null) || ("cygwin" == target."os" or null) || (("horizon" == target."os" or null) && ("arm" == target."arch" or null)));
          }
          {
            name = "libc";
            packageId = "libc";
            usesDefaultFeatures = false;
            target = {
              target,
              features,
            }: (("haiku" == target."os" or null) || ("redox" == target."os" or null) || ("nto" == target."os" or null) || ("aix" == target."os" or null));
          }
          {
            name = "libc";
            packageId = "libc";
            usesDefaultFeatures = false;
            target = {
              target,
              features,
            }: (("ios" == target."os" or null) || ("visionos" == target."os" or null) || ("watchos" == target."os" or null) || ("tvos" == target."os" or null));
          }
          {
            name = "libc";
            packageId = "libc";
            usesDefaultFeatures = false;
            target = {
              target,
              features,
            }: (("macos" == target."os" or null) || ("openbsd" == target."os" or null) || ("vita" == target."os" or null) || ("emscripten" == target."os" or null));
          }
          {
            name = "libc";
            packageId = "libc";
            usesDefaultFeatures = false;
            target = {
              target,
              features,
            }: ("netbsd" == target."os" or null);
          }
          {
            name = "libc";
            packageId = "libc";
            usesDefaultFeatures = false;
            target = {
              target,
              features,
            }: ("solaris" == target."os" or null);
          }
          {
            name = "libc";
            packageId = "libc";
            usesDefaultFeatures = false;
            target = {
              target,
              features,
            }: ("vxworks" == target."os" or null);
          }
          {
            name = "r-efi";
            packageId = "r-efi";
            usesDefaultFeatures = false;
            target = {
              target,
              features,
            }: (("uefi" == target."os" or null) && ("efi_rng" == target."getrandom_backend" or null));
          }
          {
            name = "wasip2";
            packageId = "wasip2";
            usesDefaultFeatures = false;
            target = {
              target,
              features,
            }: (("wasm32" == target."arch" or null) && ("wasi" == target."os" or null) && ("p2" == target."env" or null));
          }
          {
            name = "wasm-bindgen";
            packageId = "wasm-bindgen";
            optional = true;
            usesDefaultFeatures = false;
            target = {
              target,
              features,
            }: (("wasm32" == target."arch" or null) && (("unknown" == target."os" or null) || ("none" == target."os" or null)));
          }
        ];
        features = {
          "wasm_js" = ["dep:wasm-bindgen" "dep:js-sys"];
        };
        resolvedDefaultFeatures = ["wasm_js"];
      };
      "id_effect" = rec {
        crateName = "id_effect";
        version = "0.2.0";
        edition = "2024";
        sha256 = "19h8x3581nmmz1dmfjrcnc8lvhqn7vj51k7wzsxrdcwirkcj8vkh";
        dependencies = [
          {
            name = "flume";
            packageId = "flume";
          }
          {
            name = "futures";
            packageId = "futures";
            usesDefaultFeatures = false;
            features = ["std"];
          }
          {
            name = "id_effect_macro";
            packageId = "id_effect_macro";
          }
          {
            name = "id_effect_proc_macro";
            packageId = "id_effect_proc_macro";
          }
          {
            name = "im";
            packageId = "im";
          }
          {
            name = "jiff";
            packageId = "jiff";
          }
          {
            name = "tokio";
            packageId = "tokio";
            features = ["macros" "rt" "time" "sync"];
          }
        ];
        devDependencies = [
          {
            name = "tokio";
            packageId = "tokio";
            features = ["macros" "rt" "rt-multi-thread" "sync" "time"];
          }
        ];
        features = {
          "schema-serde" = ["dep:serde_json"];
        };
      };
      "id_effect_macro" = rec {
        crateName = "id_effect_macro";
        version = "0.2.0";
        edition = "2024";
        sha256 = "0p0w2wrirr17pwh5jwz8fjd0nxa7lycmgvc5m3x95lc3xx2si41a";
      };
      "id_effect_proc_macro" = rec {
        crateName = "id_effect_proc_macro";
        version = "0.2.0";
        edition = "2024";
        sha256 = "05mvw53afiqk0xwfpgn1s8pzh5zh3ng0v2jmv49qpvmsshaqn8rz";
        procMacro = true;
        dependencies = [
          {
            name = "proc-macro2";
            packageId = "proc-macro2";
          }
          {
            name = "quote";
            packageId = "quote";
          }
          {
            name = "syn";
            packageId = "syn";
            features = ["full"];
          }
        ];
      };
      "im" = rec {
        crateName = "im";
        version = "15.1.0";
        edition = "2018";
        sha256 = "1sg0jy9y0l3lqjpjyclj6kspi027mx177dgrmacgjni8y0zx7b6h";
        authors = [
          "Bodil Stokke <bodil@bodil.org>"
        ];
        dependencies = [
          {
            name = "bitmaps";
            packageId = "bitmaps";
          }
          {
            name = "rand_core";
            packageId = "rand_core";
          }
          {
            name = "rand_xoshiro";
            packageId = "rand_xoshiro";
          }
          {
            name = "sized-chunks";
            packageId = "sized-chunks";
          }
          {
            name = "typenum";
            packageId = "typenum";
          }
        ];
        buildDependencies = [
          {
            name = "version_check";
            packageId = "version_check";
          }
        ];
        features = {
          "arbitrary" = ["dep:arbitrary"];
          "proptest" = ["dep:proptest"];
          "quickcheck" = ["dep:quickcheck"];
          "rayon" = ["dep:rayon"];
          "refpool" = ["dep:refpool"];
          "serde" = ["dep:serde"];
        };
      };
      "jiff" = rec {
        crateName = "jiff";
        version = "0.2.23";
        edition = "2021";
        sha256 = "0nc37n7jvgrzxdkcgc2hsfdf70lfagigjalh4igjrm5njvf4cd8s";
        authors = [
          "Andrew Gallant <jamslam@gmail.com>"
        ];
        dependencies = [
          {
            name = "jiff-static";
            packageId = "jiff-static";
            optional = true;
          }
          {
            name = "jiff-static";
            packageId = "jiff-static";
            target = {
              target,
              features,
            }:
              false;
          }
          {
            name = "jiff-tzdb-platform";
            packageId = "jiff-tzdb-platform";
            optional = true;
            target = {
              target,
              features,
            }: ((target."windows" or false) || (builtins.elem "wasm" target."family"));
          }
          {
            name = "log";
            packageId = "log";
            optional = true;
            usesDefaultFeatures = false;
          }
          {
            name = "portable-atomic";
            packageId = "portable-atomic";
            usesDefaultFeatures = false;
            target = {
              target,
              features,
            }: (!("ptr" == target."has_atomic" or null));
          }
          {
            name = "portable-atomic-util";
            packageId = "portable-atomic-util";
            usesDefaultFeatures = false;
            target = {
              target,
              features,
            }: (!("ptr" == target."has_atomic" or null));
          }
          {
            name = "serde_core";
            packageId = "serde_core";
            optional = true;
            usesDefaultFeatures = false;
          }
          {
            name = "windows-sys";
            packageId = "windows-sys";
            optional = true;
            usesDefaultFeatures = false;
            target = {
              target,
              features,
            }: (target."windows" or false);
            features = ["Win32_Foundation" "Win32_System_Time"];
          }
        ];
        devDependencies = [
          {
            name = "log";
            packageId = "log";
          }
        ];
        features = {
          "alloc" = ["serde_core?/alloc" "portable-atomic-util/alloc"];
          "default" = ["std" "tz-system" "tz-fat" "tzdb-bundle-platform" "tzdb-zoneinfo" "tzdb-concatenated" "perf-inline"];
          "js" = ["dep:wasm-bindgen" "dep:js-sys"];
          "logging" = ["dep:log"];
          "serde" = ["dep:serde_core"];
          "static" = ["static-tz" "jiff-static?/tzdb"];
          "static-tz" = ["dep:jiff-static"];
          "std" = ["alloc" "log?/std" "serde_core?/std"];
          "tz-fat" = ["jiff-static?/tz-fat"];
          "tz-system" = ["std" "dep:windows-sys"];
          "tzdb-bundle-always" = ["dep:jiff-tzdb" "alloc"];
          "tzdb-bundle-platform" = ["dep:jiff-tzdb-platform" "alloc"];
          "tzdb-concatenated" = ["std"];
          "tzdb-zoneinfo" = ["std"];
        };
        resolvedDefaultFeatures = ["alloc" "default" "perf-inline" "std" "tz-fat" "tz-system" "tzdb-bundle-platform" "tzdb-concatenated" "tzdb-zoneinfo"];
      };
      "jiff-static" = rec {
        crateName = "jiff-static";
        version = "0.2.23";
        edition = "2021";
        sha256 = "192ss3cnixvg79cpa76clwkhn4mmz10vnwsbf7yjw8i484s8p31a";
        procMacro = true;
        libName = "jiff_static";
        authors = [
          "Andrew Gallant <jamslam@gmail.com>"
        ];
        dependencies = [
          {
            name = "proc-macro2";
            packageId = "proc-macro2";
          }
          {
            name = "quote";
            packageId = "quote";
          }
          {
            name = "syn";
            packageId = "syn";
          }
        ];
        features = {
          "tzdb" = ["dep:jiff-tzdb"];
        };
        resolvedDefaultFeatures = ["default" "tz-fat"];
      };
      "jiff-tzdb" = rec {
        crateName = "jiff-tzdb";
        version = "0.1.6";
        edition = "2021";
        sha256 = "0xihzlnnyk0xnrzpq4xcyjdcmy8xc3ychzb9ayjkh4vgha2fy069";
        libName = "jiff_tzdb";
        libPath = "lib.rs";
        authors = [
          "Andrew Gallant <jamslam@gmail.com>"
        ];
      };
      "jiff-tzdb-platform" = rec {
        crateName = "jiff-tzdb-platform";
        version = "0.1.3";
        edition = "2021";
        sha256 = "1s1ja692wyhbv7f60mc0x90h7kn1pv65xkqi2y4imarbmilmlnl7";
        libName = "jiff_tzdb_platform";
        libPath = "lib.rs";
        authors = [
          "Andrew Gallant <jamslam@gmail.com>"
        ];
        dependencies = [
          {
            name = "jiff-tzdb";
            packageId = "jiff-tzdb";
          }
        ];
      };
      "js-sys" = rec {
        crateName = "js-sys";
        version = "0.3.95";
        edition = "2021";
        sha256 = "1jhj3kgxxgwm0cpdjiz7i2qapqr7ya9qswadmr63dhwx3lnyjr19";
        libName = "js_sys";
        authors = [
          "The wasm-bindgen Developers"
        ];
        dependencies = [
          {
            name = "once_cell";
            packageId = "once_cell";
            usesDefaultFeatures = false;
          }
          {
            name = "wasm-bindgen";
            packageId = "wasm-bindgen";
            usesDefaultFeatures = false;
          }
        ];
        features = {
          "default" = ["std" "unsafe-eval"];
          "futures" = ["dep:cfg-if" "dep:futures-util"];
          "futures-core-03-stream" = ["futures" "dep:futures-core"];
          "std" = ["wasm-bindgen/std"];
        };
      };
      "libc" = rec {
        crateName = "libc";
        version = "0.2.185";
        edition = "2021";
        sha256 = "13rbdaa59l3w92q7kfcxx8zbikm99zzw54h59aqvcv5wx47jrzsj";
        authors = [
          "The Rust Project Developers"
        ];
        features = {
          "default" = ["std"];
          "rustc-dep-of-std" = ["align" "rustc-std-workspace-core"];
          "rustc-std-workspace-core" = ["dep:rustc-std-workspace-core"];
          "use_std" = ["std"];
        };
      };
      "lock_api" = rec {
        crateName = "lock_api";
        version = "0.4.14";
        edition = "2021";
        sha256 = "0rg9mhx7vdpajfxvdjmgmlyrn20ligzqvn8ifmaz7dc79gkrjhr2";
        authors = [
          "Amanieu d'Antras <amanieu@gmail.com>"
        ];
        dependencies = [
          {
            name = "scopeguard";
            packageId = "scopeguard";
            usesDefaultFeatures = false;
          }
        ];
        features = {
          "default" = ["atomic_usize"];
          "owning_ref" = ["dep:owning_ref"];
          "serde" = ["dep:serde"];
        };
        resolvedDefaultFeatures = ["atomic_usize" "default"];
      };
      "log" = rec {
        crateName = "log";
        version = "0.4.29";
        edition = "2021";
        sha256 = "15q8j9c8g5zpkcw0hnd6cf2z7fxqnvsjh3rw5mv5q10r83i34l2y";
        authors = [
          "The Rust Project Developers"
        ];
        features = {
          "kv_serde" = ["kv_std" "value-bag/serde" "serde"];
          "kv_std" = ["std" "kv" "value-bag/error"];
          "kv_sval" = ["kv" "value-bag/sval" "sval" "sval_ref"];
          "kv_unstable" = ["kv" "value-bag"];
          "kv_unstable_serde" = ["kv_serde" "kv_unstable_std"];
          "kv_unstable_std" = ["kv_std" "kv_unstable"];
          "kv_unstable_sval" = ["kv_sval" "kv_unstable"];
          "serde" = ["serde_core"];
          "serde_core" = ["dep:serde_core"];
          "sval" = ["dep:sval"];
          "sval_ref" = ["dep:sval_ref"];
          "value-bag" = ["dep:value-bag"];
        };
        resolvedDefaultFeatures = ["std"];
      };
      "ls" = rec {
        crateName = "ls";
        version = "0.1.0";
        edition = "2024";
        crateBin = [
          {
            name = "ls";
            path = "src/main.rs";
            requiredFeatures = [];
          }
        ];
        src = lib.cleanSourceWith {
          filter = sourceFilter;
          src = ./.;
        };
        authors = [
          "Industrial <tom.wieland@gmail.com>"
        ];
        dependencies = [
          {
            name = "id_effect";
            packageId = "id_effect";
          }
        ];
      };
      "memchr" = rec {
        crateName = "memchr";
        version = "2.8.0";
        edition = "2021";
        sha256 = "0y9zzxcqxvdqg6wyag7vc3h0blhdn7hkq164bxyx2vph8zs5ijpq";
        authors = [
          "Andrew Gallant <jamslam@gmail.com>"
          "bluss"
        ];
        features = {
          "core" = ["dep:core"];
          "default" = ["std"];
          "logging" = ["dep:log"];
          "rustc-dep-of-std" = ["core"];
          "std" = ["alloc"];
          "use_std" = ["std"];
        };
        resolvedDefaultFeatures = ["alloc" "default" "std"];
      };
      "once_cell" = rec {
        crateName = "once_cell";
        version = "1.21.4";
        edition = "2021";
        sha256 = "0l1v676wf71kjg2khch4dphwh1jp3291ffiymr2mvy1kxd5kwz4z";
        authors = [
          "Aleksey Kladov <aleksey.kladov@gmail.com>"
        ];
        features = {
          "alloc" = ["race"];
          "atomic-polyfill" = ["critical-section"];
          "critical-section" = ["dep:critical-section" "portable-atomic"];
          "default" = ["std"];
          "parking_lot" = ["dep:parking_lot_core"];
          "portable-atomic" = ["dep:portable-atomic"];
          "std" = ["alloc"];
        };
      };
      "pin-project-lite" = rec {
        crateName = "pin-project-lite";
        version = "0.2.17";
        edition = "2018";
        sha256 = "1kfmwvs271si96zay4mm8887v5khw0c27jc9srw1a75ykvgj54x8";
        libName = "pin_project_lite";
      };
      "portable-atomic" = rec {
        crateName = "portable-atomic";
        version = "1.13.1";
        edition = "2018";
        sha256 = "0j8vlar3n5acyigq8q6f4wjx3k3s5yz0rlpqrv76j73gi5qr8fn3";
        libName = "portable_atomic";
        features = {
          "critical-section" = ["dep:critical-section"];
          "default" = ["fallback"];
          "serde" = ["dep:serde"];
        };
        resolvedDefaultFeatures = ["require-cas"];
      };
      "portable-atomic-util" = rec {
        crateName = "portable-atomic-util";
        version = "0.2.7";
        edition = "2018";
        sha256 = "0616j0fhy6y71hyxg3n86f6hng0fmsc269s3wp4gl8ww4p8hd8f2";
        libName = "portable_atomic_util";
        dependencies = [
          {
            name = "portable-atomic";
            packageId = "portable-atomic";
            usesDefaultFeatures = false;
            features = ["require-cas"];
          }
        ];
        features = {
          "serde" = ["dep:serde"];
          "std" = ["alloc"];
        };
        resolvedDefaultFeatures = ["alloc"];
      };
      "proc-macro2" = rec {
        crateName = "proc-macro2";
        version = "1.0.106";
        edition = "2021";
        sha256 = "0d09nczyaj67x4ihqr5p7gxbkz38gxhk4asc0k8q23g9n85hzl4g";
        libName = "proc_macro2";
        authors = [
          "David Tolnay <dtolnay@gmail.com>"
          "Alex Crichton <alex@alexcrichton.com>"
        ];
        dependencies = [
          {
            name = "unicode-ident";
            packageId = "unicode-ident";
          }
        ];
        features = {
          "default" = ["proc-macro"];
        };
        resolvedDefaultFeatures = ["default" "proc-macro"];
      };
      "quote" = rec {
        crateName = "quote";
        version = "1.0.45";
        edition = "2021";
        sha256 = "095rb5rg7pbnwdp6v8w5jw93wndwyijgci1b5lw8j1h5cscn3wj1";
        authors = [
          "David Tolnay <dtolnay@gmail.com>"
        ];
        dependencies = [
          {
            name = "proc-macro2";
            packageId = "proc-macro2";
            usesDefaultFeatures = false;
          }
        ];
        features = {
          "default" = ["proc-macro"];
          "proc-macro" = ["proc-macro2/proc-macro"];
        };
        resolvedDefaultFeatures = ["default" "proc-macro"];
      };
      "r-efi" = rec {
        crateName = "r-efi";
        version = "5.3.0";
        edition = "2018";
        sha256 = "03sbfm3g7myvzyylff6qaxk4z6fy76yv860yy66jiswc2m6b7kb9";
        libName = "r_efi";
        features = {
          "core" = ["dep:core"];
          "examples" = ["native"];
          "rustc-dep-of-std" = ["core"];
        };
      };
      "rand_core" = rec {
        crateName = "rand_core";
        version = "0.6.4";
        edition = "2018";
        sha256 = "0b4j2v4cb5krak1pv6kakv4sz6xcwbrmy2zckc32hsigbrwy82zc";
        authors = [
          "The Rand Project Developers"
          "The Rust Project Developers"
        ];
        features = {
          "getrandom" = ["dep:getrandom"];
          "serde" = ["dep:serde"];
          "serde1" = ["serde"];
          "std" = ["alloc" "getrandom" "getrandom/std"];
        };
      };
      "rand_xoshiro" = rec {
        crateName = "rand_xoshiro";
        version = "0.6.0";
        edition = "2018";
        sha256 = "1ajsic84rzwz5qr0mzlay8vi17swqi684bqvwqyiim3flfrcv5vg";
        authors = [
          "The Rand Project Developers"
        ];
        dependencies = [
          {
            name = "rand_core";
            packageId = "rand_core";
          }
        ];
        features = {
          "serde" = ["dep:serde"];
          "serde1" = ["serde"];
        };
      };
      "rustversion" = rec {
        crateName = "rustversion";
        version = "1.0.22";
        edition = "2018";
        sha256 = "0vfl70jhv72scd9rfqgr2n11m5i9l1acnk684m2w83w0zbqdx75k";
        procMacro = true;
        build = "build/build.rs";
        authors = [
          "David Tolnay <dtolnay@gmail.com>"
        ];
      };
      "scopeguard" = rec {
        crateName = "scopeguard";
        version = "1.2.0";
        edition = "2015";
        sha256 = "0jcz9sd47zlsgcnm1hdw0664krxwb5gczlif4qngj2aif8vky54l";
        authors = [
          "bluss"
        ];
        features = {
          "default" = ["use_std"];
        };
      };
      "serde_core" = rec {
        crateName = "serde_core";
        version = "1.0.228";
        edition = "2021";
        sha256 = "1bb7id2xwx8izq50098s5j2sqrrvk31jbbrjqygyan6ask3qbls1";
        authors = [
          "Erick Tryzelaar <erick.tryzelaar@gmail.com>"
          "David Tolnay <dtolnay@gmail.com>"
        ];
        dependencies = [
          {
            name = "serde_derive";
            packageId = "serde_derive";
            target = {
              target,
              features,
            }:
              false;
          }
        ];
        devDependencies = [
          {
            name = "serde_derive";
            packageId = "serde_derive";
          }
        ];
        features = {
          "default" = ["std" "result"];
        };
        resolvedDefaultFeatures = ["alloc" "std"];
      };
      "serde_derive" = rec {
        crateName = "serde_derive";
        version = "1.0.228";
        edition = "2021";
        sha256 = "0y8xm7fvmr2kjcd029g9fijpndh8csv5m20g4bd76w8qschg4h6m";
        procMacro = true;
        authors = [
          "Erick Tryzelaar <erick.tryzelaar@gmail.com>"
          "David Tolnay <dtolnay@gmail.com>"
        ];
        dependencies = [
          {
            name = "proc-macro2";
            packageId = "proc-macro2";
            usesDefaultFeatures = false;
            features = ["proc-macro"];
          }
          {
            name = "quote";
            packageId = "quote";
            usesDefaultFeatures = false;
            features = ["proc-macro"];
          }
          {
            name = "syn";
            packageId = "syn";
            usesDefaultFeatures = false;
            features = ["clone-impls" "derive" "parsing" "printing" "proc-macro"];
          }
        ];
        features = {
        };
        resolvedDefaultFeatures = ["default"];
      };
      "sized-chunks" = rec {
        crateName = "sized-chunks";
        version = "0.6.5";
        edition = "2018";
        sha256 = "07ix5fsdnpf2xsb0k5rbiwlmsicm2237fcx7blirp9p7pljr5mhn";
        libName = "sized_chunks";
        authors = [
          "Bodil Stokke <bodil@bodil.org>"
        ];
        dependencies = [
          {
            name = "bitmaps";
            packageId = "bitmaps";
          }
          {
            name = "typenum";
            packageId = "typenum";
          }
        ];
        features = {
          "arbitrary" = ["dep:arbitrary"];
          "array-ops" = ["dep:array-ops"];
          "default" = ["std"];
          "refpool" = ["dep:refpool"];
          "ringbuffer" = ["array-ops"];
        };
        resolvedDefaultFeatures = ["default" "std"];
      };
      "slab" = rec {
        crateName = "slab";
        version = "0.4.12";
        edition = "2018";
        sha256 = "1xcwik6s6zbd3lf51kkrcicdq2j4c1fw0yjdai2apy9467i0sy8c";
        authors = [
          "Carl Lerche <me@carllerche.com>"
        ];
        features = {
          "default" = ["std"];
          "serde" = ["dep:serde"];
        };
        resolvedDefaultFeatures = ["std"];
      };
      "spin" = rec {
        crateName = "spin";
        version = "0.9.8";
        edition = "2015";
        sha256 = "0rvam5r0p3a6qhc18scqpvpgb3ckzyqxpgdfyjnghh8ja7byi039";
        authors = [
          "Mathijs van de Nes <git@mathijs.vd-nes.nl>"
          "John Ericson <git@JohnEricson.me>"
          "Joshua Barretto <joshua.s.barretto@gmail.com>"
        ];
        dependencies = [
          {
            name = "lock_api";
            packageId = "lock_api";
            rename = "lock_api_crate";
            optional = true;
          }
        ];
        features = {
          "barrier" = ["mutex"];
          "default" = ["lock_api" "mutex" "spin_mutex" "rwlock" "once" "lazy" "barrier"];
          "fair_mutex" = ["mutex"];
          "lazy" = ["once"];
          "lock_api" = ["lock_api_crate"];
          "lock_api_crate" = ["dep:lock_api_crate"];
          "portable-atomic" = ["dep:portable-atomic"];
          "portable_atomic" = ["portable-atomic"];
          "spin_mutex" = ["mutex"];
          "ticket_mutex" = ["mutex"];
          "use_ticket_mutex" = ["mutex" "ticket_mutex"];
        };
        resolvedDefaultFeatures = ["barrier" "default" "lazy" "lock_api" "lock_api_crate" "mutex" "once" "rwlock" "spin_mutex"];
      };
      "syn" = rec {
        crateName = "syn";
        version = "2.0.117";
        edition = "2021";
        sha256 = "16cv7c0wbn8amxc54n4w15kxlx5ypdmla8s0gxr2l7bv7s0bhrg6";
        authors = [
          "David Tolnay <dtolnay@gmail.com>"
        ];
        dependencies = [
          {
            name = "proc-macro2";
            packageId = "proc-macro2";
            usesDefaultFeatures = false;
          }
          {
            name = "quote";
            packageId = "quote";
            optional = true;
            usesDefaultFeatures = false;
          }
          {
            name = "unicode-ident";
            packageId = "unicode-ident";
          }
        ];
        features = {
          "default" = ["derive" "parsing" "printing" "clone-impls" "proc-macro"];
          "printing" = ["dep:quote"];
          "proc-macro" = ["proc-macro2/proc-macro" "quote?/proc-macro"];
          "test" = ["syn-test-suite/all-features"];
        };
        resolvedDefaultFeatures = ["clone-impls" "default" "derive" "extra-traits" "full" "parsing" "printing" "proc-macro" "visit" "visit-mut"];
      };
      "tokio" = rec {
        crateName = "tokio";
        version = "1.52.1";
        edition = "2021";
        sha256 = "1imw1dkkv38p66i33m5hsyk3d6prsbyrayjvqhndjvz89ybywzdn";
        authors = [
          "Tokio Contributors <team@tokio.rs>"
        ];
        dependencies = [
          {
            name = "pin-project-lite";
            packageId = "pin-project-lite";
          }
          {
            name = "tokio-macros";
            packageId = "tokio-macros";
            optional = true;
          }
        ];
        features = {
          "bytes" = ["dep:bytes"];
          "full" = ["fs" "io-util" "io-std" "macros" "net" "parking_lot" "process" "rt" "rt-multi-thread" "signal" "sync" "time"];
          "io-uring" = ["dep:io-uring" "libc" "mio/os-poll" "mio/os-ext" "dep:slab"];
          "io-util" = ["bytes"];
          "libc" = ["dep:libc"];
          "macros" = ["tokio-macros"];
          "mio" = ["dep:mio"];
          "net" = ["libc" "mio/os-poll" "mio/os-ext" "mio/net" "socket2" "windows-sys/Win32_Foundation" "windows-sys/Win32_Security" "windows-sys/Win32_Storage_FileSystem" "windows-sys/Win32_System_Pipes" "windows-sys/Win32_System_SystemServices"];
          "parking_lot" = ["dep:parking_lot"];
          "process" = ["bytes" "libc" "mio/os-poll" "mio/os-ext" "mio/net" "signal-hook-registry" "windows-sys/Win32_Foundation" "windows-sys/Win32_System_Threading" "windows-sys/Win32_System_WindowsProgramming"];
          "rt-multi-thread" = ["rt"];
          "signal" = ["libc" "mio/os-poll" "mio/net" "mio/os-ext" "signal-hook-registry" "windows-sys/Win32_Foundation" "windows-sys/Win32_System_Console"];
          "signal-hook-registry" = ["dep:signal-hook-registry"];
          "socket2" = ["dep:socket2"];
          "taskdump" = ["dep:backtrace"];
          "test-util" = ["rt" "sync" "time"];
          "tokio-macros" = ["dep:tokio-macros"];
          "tracing" = ["dep:tracing"];
          "windows-sys" = ["dep:windows-sys"];
        };
        resolvedDefaultFeatures = ["default" "macros" "rt" "sync" "time" "tokio-macros"];
      };
      "tokio-macros" = rec {
        crateName = "tokio-macros";
        version = "2.7.0";
        edition = "2021";
        sha256 = "15m4f37mdafs0gg36sh0rskm1i768lb7zmp8bw67kaxr3avnqniq";
        procMacro = true;
        libName = "tokio_macros";
        authors = [
          "Tokio Contributors <team@tokio.rs>"
        ];
        dependencies = [
          {
            name = "proc-macro2";
            packageId = "proc-macro2";
          }
          {
            name = "quote";
            packageId = "quote";
          }
          {
            name = "syn";
            packageId = "syn";
            features = ["full"];
          }
        ];
      };
      "typenum" = rec {
        crateName = "typenum";
        version = "1.19.0";
        edition = "2018";
        sha256 = "1fw2mpbn2vmqan56j1b3fbpcdg80mz26fm53fs16bq5xcq84hban";
        authors = [
          "Paho Lurie-Gregg <paho@paholg.com>"
          "Andre Bogus <bogusandre@gmail.com>"
        ];
        features = {
          "scale-info" = ["dep:scale-info"];
          "scale_info" = ["scale-info/derive"];
        };
      };
      "unicode-ident" = rec {
        crateName = "unicode-ident";
        version = "1.0.24";
        edition = "2021";
        sha256 = "0xfs8y1g7syl2iykji8zk5hgfi5jw819f5zsrbaxmlzwsly33r76";
        libName = "unicode_ident";
        authors = [
          "David Tolnay <dtolnay@gmail.com>"
        ];
      };
      "version_check" = rec {
        crateName = "version_check";
        version = "0.9.5";
        edition = "2015";
        sha256 = "0nhhi4i5x89gm911azqbn7avs9mdacw2i3vcz3cnmz3mv4rqz4hb";
        authors = [
          "Sergio Benitez <sb@sergio.bz>"
        ];
      };
      "wasip2" = rec {
        crateName = "wasip2";
        version = "1.0.3+wasi-0.2.9";
        edition = "2021";
        sha256 = "1mi3w855dz99xzjqc4aa8c9q5b6z1y5c963pkk4cvmr6vdr4c1i0";
        dependencies = [
          {
            name = "wit-bindgen";
            packageId = "wit-bindgen";
            usesDefaultFeatures = false;
          }
        ];
        features = {
          "alloc" = ["dep:alloc"];
          "bitflags" = ["wit-bindgen/bitflags"];
          "core" = ["dep:core"];
          "default" = ["std" "bitflags"];
          "rustc-dep-of-std" = ["core" "alloc" "wit-bindgen/rustc-dep-of-std"];
        };
      };
      "wasm-bindgen" = rec {
        crateName = "wasm-bindgen";
        version = "0.2.118";
        edition = "2021";
        sha256 = "129s5r14fx4v4xrzpx2c6l860nkxpl48j50y7kl6j16bpah3iy8b";
        libName = "wasm_bindgen";
        authors = [
          "The wasm-bindgen Developers"
        ];
        dependencies = [
          {
            name = "cfg-if";
            packageId = "cfg-if";
          }
          {
            name = "once_cell";
            packageId = "once_cell";
            usesDefaultFeatures = false;
          }
          {
            name = "wasm-bindgen-macro";
            packageId = "wasm-bindgen-macro";
          }
          {
            name = "wasm-bindgen-shared";
            packageId = "wasm-bindgen-shared";
          }
        ];
        buildDependencies = [
          {
            name = "rustversion";
            packageId = "rustversion";
            rename = "rustversion-compat";
          }
        ];
        devDependencies = [
          {
            name = "once_cell";
            packageId = "once_cell";
          }
        ];
        features = {
          "default" = ["std"];
          "enable-interning" = ["std"];
          "serde" = ["dep:serde"];
          "serde-serialize" = ["serde" "serde_json" "std"];
          "serde_json" = ["dep:serde_json"];
          "strict-macro" = ["wasm-bindgen-macro/strict-macro"];
        };
      };
      "wasm-bindgen-macro" = rec {
        crateName = "wasm-bindgen-macro";
        version = "0.2.118";
        edition = "2021";
        sha256 = "1v98r8vs17cj8918qsg0xx4nlg4nxk1g0jd4nwnyrh1687w29zzf";
        procMacro = true;
        libName = "wasm_bindgen_macro";
        authors = [
          "The wasm-bindgen Developers"
        ];
        dependencies = [
          {
            name = "quote";
            packageId = "quote";
          }
          {
            name = "wasm-bindgen-macro-support";
            packageId = "wasm-bindgen-macro-support";
          }
        ];
        features = {
          "strict-macro" = ["wasm-bindgen-macro-support/strict-macro"];
        };
      };
      "wasm-bindgen-macro-support" = rec {
        crateName = "wasm-bindgen-macro-support";
        version = "0.2.118";
        edition = "2021";
        sha256 = "0169jr0q469hfx5zqxfyywf2h2f4aj17vn4zly02nfwqmxghc24x";
        libName = "wasm_bindgen_macro_support";
        authors = [
          "The wasm-bindgen Developers"
        ];
        dependencies = [
          {
            name = "bumpalo";
            packageId = "bumpalo";
          }
          {
            name = "proc-macro2";
            packageId = "proc-macro2";
          }
          {
            name = "quote";
            packageId = "quote";
          }
          {
            name = "syn";
            packageId = "syn";
            features = ["visit" "visit-mut" "full" "extra-traits"];
          }
          {
            name = "wasm-bindgen-shared";
            packageId = "wasm-bindgen-shared";
          }
        ];
        features = {
          "extra-traits" = ["syn/extra-traits"];
        };
      };
      "wasm-bindgen-shared" = rec {
        crateName = "wasm-bindgen-shared";
        version = "0.2.118";
        edition = "2021";
        links = "wasm_bindgen";
        sha256 = "0ag1vvdzi4334jlzilsy14y3nyzwddf1ndn62fyhf6bg62g4vl2z";
        libName = "wasm_bindgen_shared";
        authors = [
          "The wasm-bindgen Developers"
        ];
        dependencies = [
          {
            name = "unicode-ident";
            packageId = "unicode-ident";
          }
        ];
      };
      "windows-link" = rec {
        crateName = "windows-link";
        version = "0.2.1";
        edition = "2021";
        sha256 = "1rag186yfr3xx7piv5rg8b6im2dwcf8zldiflvb22xbzwli5507h";
        libName = "windows_link";
      };
      "windows-sys" = rec {
        crateName = "windows-sys";
        version = "0.61.2";
        edition = "2021";
        sha256 = "1z7k3y9b6b5h52kid57lvmvm05362zv1v8w0gc7xyv5xphlp44xf";
        libName = "windows_sys";
        dependencies = [
          {
            name = "windows-link";
            packageId = "windows-link";
            usesDefaultFeatures = false;
          }
        ];
        features = {
          "Wdk" = ["Win32_Foundation"];
          "Wdk_Devices" = ["Wdk"];
          "Wdk_Devices_Bluetooth" = ["Wdk_Devices"];
          "Wdk_Devices_HumanInterfaceDevice" = ["Wdk_Devices"];
          "Wdk_Foundation" = ["Wdk"];
          "Wdk_Graphics" = ["Wdk"];
          "Wdk_Graphics_Direct3D" = ["Wdk_Graphics"];
          "Wdk_NetworkManagement" = ["Wdk"];
          "Wdk_NetworkManagement_Ndis" = ["Wdk_NetworkManagement"];
          "Wdk_NetworkManagement_WindowsFilteringPlatform" = ["Wdk_NetworkManagement"];
          "Wdk_Storage" = ["Wdk"];
          "Wdk_Storage_FileSystem" = ["Wdk_Storage"];
          "Wdk_Storage_FileSystem_Minifilters" = ["Wdk_Storage_FileSystem"];
          "Wdk_System" = ["Wdk"];
          "Wdk_System_IO" = ["Wdk_System"];
          "Wdk_System_Memory" = ["Wdk_System"];
          "Wdk_System_OfflineRegistry" = ["Wdk_System"];
          "Wdk_System_Registry" = ["Wdk_System"];
          "Wdk_System_SystemInformation" = ["Wdk_System"];
          "Wdk_System_SystemServices" = ["Wdk_System"];
          "Wdk_System_Threading" = ["Wdk_System"];
          "Win32" = ["Win32_Foundation"];
          "Win32_Data" = ["Win32"];
          "Win32_Data_HtmlHelp" = ["Win32_Data"];
          "Win32_Data_RightsManagement" = ["Win32_Data"];
          "Win32_Devices" = ["Win32"];
          "Win32_Devices_AllJoyn" = ["Win32_Devices"];
          "Win32_Devices_Beep" = ["Win32_Devices"];
          "Win32_Devices_BiometricFramework" = ["Win32_Devices"];
          "Win32_Devices_Bluetooth" = ["Win32_Devices"];
          "Win32_Devices_Cdrom" = ["Win32_Devices"];
          "Win32_Devices_Communication" = ["Win32_Devices"];
          "Win32_Devices_DeviceAndDriverInstallation" = ["Win32_Devices"];
          "Win32_Devices_DeviceQuery" = ["Win32_Devices"];
          "Win32_Devices_Display" = ["Win32_Devices"];
          "Win32_Devices_Dvd" = ["Win32_Devices"];
          "Win32_Devices_Enumeration" = ["Win32_Devices"];
          "Win32_Devices_Enumeration_Pnp" = ["Win32_Devices_Enumeration"];
          "Win32_Devices_Fax" = ["Win32_Devices"];
          "Win32_Devices_HumanInterfaceDevice" = ["Win32_Devices"];
          "Win32_Devices_Nfc" = ["Win32_Devices"];
          "Win32_Devices_Nfp" = ["Win32_Devices"];
          "Win32_Devices_PortableDevices" = ["Win32_Devices"];
          "Win32_Devices_Properties" = ["Win32_Devices"];
          "Win32_Devices_Pwm" = ["Win32_Devices"];
          "Win32_Devices_Sensors" = ["Win32_Devices"];
          "Win32_Devices_SerialCommunication" = ["Win32_Devices"];
          "Win32_Devices_Tapi" = ["Win32_Devices"];
          "Win32_Devices_Usb" = ["Win32_Devices"];
          "Win32_Devices_WebServicesOnDevices" = ["Win32_Devices"];
          "Win32_Foundation" = ["Win32"];
          "Win32_Gaming" = ["Win32"];
          "Win32_Globalization" = ["Win32"];
          "Win32_Graphics" = ["Win32"];
          "Win32_Graphics_Dwm" = ["Win32_Graphics"];
          "Win32_Graphics_Gdi" = ["Win32_Graphics"];
          "Win32_Graphics_GdiPlus" = ["Win32_Graphics"];
          "Win32_Graphics_Hlsl" = ["Win32_Graphics"];
          "Win32_Graphics_OpenGL" = ["Win32_Graphics"];
          "Win32_Graphics_Printing" = ["Win32_Graphics"];
          "Win32_Graphics_Printing_PrintTicket" = ["Win32_Graphics_Printing"];
          "Win32_Management" = ["Win32"];
          "Win32_Management_MobileDeviceManagementRegistration" = ["Win32_Management"];
          "Win32_Media" = ["Win32"];
          "Win32_Media_Audio" = ["Win32_Media"];
          "Win32_Media_DxMediaObjects" = ["Win32_Media"];
          "Win32_Media_KernelStreaming" = ["Win32_Media"];
          "Win32_Media_Multimedia" = ["Win32_Media"];
          "Win32_Media_Streaming" = ["Win32_Media"];
          "Win32_Media_WindowsMediaFormat" = ["Win32_Media"];
          "Win32_NetworkManagement" = ["Win32"];
          "Win32_NetworkManagement_Dhcp" = ["Win32_NetworkManagement"];
          "Win32_NetworkManagement_Dns" = ["Win32_NetworkManagement"];
          "Win32_NetworkManagement_InternetConnectionWizard" = ["Win32_NetworkManagement"];
          "Win32_NetworkManagement_IpHelper" = ["Win32_NetworkManagement"];
          "Win32_NetworkManagement_Multicast" = ["Win32_NetworkManagement"];
          "Win32_NetworkManagement_Ndis" = ["Win32_NetworkManagement"];
          "Win32_NetworkManagement_NetBios" = ["Win32_NetworkManagement"];
          "Win32_NetworkManagement_NetManagement" = ["Win32_NetworkManagement"];
          "Win32_NetworkManagement_NetShell" = ["Win32_NetworkManagement"];
          "Win32_NetworkManagement_NetworkDiagnosticsFramework" = ["Win32_NetworkManagement"];
          "Win32_NetworkManagement_P2P" = ["Win32_NetworkManagement"];
          "Win32_NetworkManagement_QoS" = ["Win32_NetworkManagement"];
          "Win32_NetworkManagement_Rras" = ["Win32_NetworkManagement"];
          "Win32_NetworkManagement_Snmp" = ["Win32_NetworkManagement"];
          "Win32_NetworkManagement_WNet" = ["Win32_NetworkManagement"];
          "Win32_NetworkManagement_WebDav" = ["Win32_NetworkManagement"];
          "Win32_NetworkManagement_WiFi" = ["Win32_NetworkManagement"];
          "Win32_NetworkManagement_WindowsConnectionManager" = ["Win32_NetworkManagement"];
          "Win32_NetworkManagement_WindowsFilteringPlatform" = ["Win32_NetworkManagement"];
          "Win32_NetworkManagement_WindowsFirewall" = ["Win32_NetworkManagement"];
          "Win32_NetworkManagement_WindowsNetworkVirtualization" = ["Win32_NetworkManagement"];
          "Win32_Networking" = ["Win32"];
          "Win32_Networking_ActiveDirectory" = ["Win32_Networking"];
          "Win32_Networking_Clustering" = ["Win32_Networking"];
          "Win32_Networking_HttpServer" = ["Win32_Networking"];
          "Win32_Networking_Ldap" = ["Win32_Networking"];
          "Win32_Networking_WebSocket" = ["Win32_Networking"];
          "Win32_Networking_WinHttp" = ["Win32_Networking"];
          "Win32_Networking_WinInet" = ["Win32_Networking"];
          "Win32_Networking_WinSock" = ["Win32_Networking"];
          "Win32_Networking_WindowsWebServices" = ["Win32_Networking"];
          "Win32_Security" = ["Win32"];
          "Win32_Security_AppLocker" = ["Win32_Security"];
          "Win32_Security_Authentication" = ["Win32_Security"];
          "Win32_Security_Authentication_Identity" = ["Win32_Security_Authentication"];
          "Win32_Security_Authorization" = ["Win32_Security"];
          "Win32_Security_Credentials" = ["Win32_Security"];
          "Win32_Security_Cryptography" = ["Win32_Security"];
          "Win32_Security_Cryptography_Catalog" = ["Win32_Security_Cryptography"];
          "Win32_Security_Cryptography_Certificates" = ["Win32_Security_Cryptography"];
          "Win32_Security_Cryptography_Sip" = ["Win32_Security_Cryptography"];
          "Win32_Security_Cryptography_UI" = ["Win32_Security_Cryptography"];
          "Win32_Security_DiagnosticDataQuery" = ["Win32_Security"];
          "Win32_Security_DirectoryServices" = ["Win32_Security"];
          "Win32_Security_EnterpriseData" = ["Win32_Security"];
          "Win32_Security_ExtensibleAuthenticationProtocol" = ["Win32_Security"];
          "Win32_Security_Isolation" = ["Win32_Security"];
          "Win32_Security_LicenseProtection" = ["Win32_Security"];
          "Win32_Security_NetworkAccessProtection" = ["Win32_Security"];
          "Win32_Security_WinTrust" = ["Win32_Security"];
          "Win32_Security_WinWlx" = ["Win32_Security"];
          "Win32_Storage" = ["Win32"];
          "Win32_Storage_Cabinets" = ["Win32_Storage"];
          "Win32_Storage_CloudFilters" = ["Win32_Storage"];
          "Win32_Storage_Compression" = ["Win32_Storage"];
          "Win32_Storage_DistributedFileSystem" = ["Win32_Storage"];
          "Win32_Storage_FileHistory" = ["Win32_Storage"];
          "Win32_Storage_FileSystem" = ["Win32_Storage"];
          "Win32_Storage_Imapi" = ["Win32_Storage"];
          "Win32_Storage_IndexServer" = ["Win32_Storage"];
          "Win32_Storage_InstallableFileSystems" = ["Win32_Storage"];
          "Win32_Storage_IscsiDisc" = ["Win32_Storage"];
          "Win32_Storage_Jet" = ["Win32_Storage"];
          "Win32_Storage_Nvme" = ["Win32_Storage"];
          "Win32_Storage_OfflineFiles" = ["Win32_Storage"];
          "Win32_Storage_OperationRecorder" = ["Win32_Storage"];
          "Win32_Storage_Packaging" = ["Win32_Storage"];
          "Win32_Storage_Packaging_Appx" = ["Win32_Storage_Packaging"];
          "Win32_Storage_ProjectedFileSystem" = ["Win32_Storage"];
          "Win32_Storage_StructuredStorage" = ["Win32_Storage"];
          "Win32_Storage_Vhd" = ["Win32_Storage"];
          "Win32_Storage_Xps" = ["Win32_Storage"];
          "Win32_System" = ["Win32"];
          "Win32_System_AddressBook" = ["Win32_System"];
          "Win32_System_Antimalware" = ["Win32_System"];
          "Win32_System_ApplicationInstallationAndServicing" = ["Win32_System"];
          "Win32_System_ApplicationVerifier" = ["Win32_System"];
          "Win32_System_ClrHosting" = ["Win32_System"];
          "Win32_System_Com" = ["Win32_System"];
          "Win32_System_Com_Marshal" = ["Win32_System_Com"];
          "Win32_System_Com_StructuredStorage" = ["Win32_System_Com"];
          "Win32_System_Com_Urlmon" = ["Win32_System_Com"];
          "Win32_System_ComponentServices" = ["Win32_System"];
          "Win32_System_Console" = ["Win32_System"];
          "Win32_System_CorrelationVector" = ["Win32_System"];
          "Win32_System_DataExchange" = ["Win32_System"];
          "Win32_System_DeploymentServices" = ["Win32_System"];
          "Win32_System_DeveloperLicensing" = ["Win32_System"];
          "Win32_System_Diagnostics" = ["Win32_System"];
          "Win32_System_Diagnostics_Ceip" = ["Win32_System_Diagnostics"];
          "Win32_System_Diagnostics_Debug" = ["Win32_System_Diagnostics"];
          "Win32_System_Diagnostics_Debug_Extensions" = ["Win32_System_Diagnostics_Debug"];
          "Win32_System_Diagnostics_Etw" = ["Win32_System_Diagnostics"];
          "Win32_System_Diagnostics_ProcessSnapshotting" = ["Win32_System_Diagnostics"];
          "Win32_System_Diagnostics_ToolHelp" = ["Win32_System_Diagnostics"];
          "Win32_System_Diagnostics_TraceLogging" = ["Win32_System_Diagnostics"];
          "Win32_System_DistributedTransactionCoordinator" = ["Win32_System"];
          "Win32_System_Environment" = ["Win32_System"];
          "Win32_System_ErrorReporting" = ["Win32_System"];
          "Win32_System_EventCollector" = ["Win32_System"];
          "Win32_System_EventLog" = ["Win32_System"];
          "Win32_System_EventNotificationService" = ["Win32_System"];
          "Win32_System_GroupPolicy" = ["Win32_System"];
          "Win32_System_HostCompute" = ["Win32_System"];
          "Win32_System_HostComputeNetwork" = ["Win32_System"];
          "Win32_System_HostComputeSystem" = ["Win32_System"];
          "Win32_System_Hypervisor" = ["Win32_System"];
          "Win32_System_IO" = ["Win32_System"];
          "Win32_System_Iis" = ["Win32_System"];
          "Win32_System_Ioctl" = ["Win32_System"];
          "Win32_System_JobObjects" = ["Win32_System"];
          "Win32_System_Js" = ["Win32_System"];
          "Win32_System_Kernel" = ["Win32_System"];
          "Win32_System_LibraryLoader" = ["Win32_System"];
          "Win32_System_Mailslots" = ["Win32_System"];
          "Win32_System_Mapi" = ["Win32_System"];
          "Win32_System_Memory" = ["Win32_System"];
          "Win32_System_Memory_NonVolatile" = ["Win32_System_Memory"];
          "Win32_System_MessageQueuing" = ["Win32_System"];
          "Win32_System_MixedReality" = ["Win32_System"];
          "Win32_System_Ole" = ["Win32_System"];
          "Win32_System_PasswordManagement" = ["Win32_System"];
          "Win32_System_Performance" = ["Win32_System"];
          "Win32_System_Performance_HardwareCounterProfiling" = ["Win32_System_Performance"];
          "Win32_System_Pipes" = ["Win32_System"];
          "Win32_System_Power" = ["Win32_System"];
          "Win32_System_ProcessStatus" = ["Win32_System"];
          "Win32_System_Recovery" = ["Win32_System"];
          "Win32_System_Registry" = ["Win32_System"];
          "Win32_System_RemoteDesktop" = ["Win32_System"];
          "Win32_System_RemoteManagement" = ["Win32_System"];
          "Win32_System_RestartManager" = ["Win32_System"];
          "Win32_System_Restore" = ["Win32_System"];
          "Win32_System_Rpc" = ["Win32_System"];
          "Win32_System_Search" = ["Win32_System"];
          "Win32_System_Search_Common" = ["Win32_System_Search"];
          "Win32_System_SecurityCenter" = ["Win32_System"];
          "Win32_System_Services" = ["Win32_System"];
          "Win32_System_SetupAndMigration" = ["Win32_System"];
          "Win32_System_Shutdown" = ["Win32_System"];
          "Win32_System_StationsAndDesktops" = ["Win32_System"];
          "Win32_System_SubsystemForLinux" = ["Win32_System"];
          "Win32_System_SystemInformation" = ["Win32_System"];
          "Win32_System_SystemServices" = ["Win32_System"];
          "Win32_System_Threading" = ["Win32_System"];
          "Win32_System_Time" = ["Win32_System"];
          "Win32_System_TpmBaseServices" = ["Win32_System"];
          "Win32_System_UserAccessLogging" = ["Win32_System"];
          "Win32_System_Variant" = ["Win32_System"];
          "Win32_System_VirtualDosMachines" = ["Win32_System"];
          "Win32_System_WindowsProgramming" = ["Win32_System"];
          "Win32_System_Wmi" = ["Win32_System"];
          "Win32_UI" = ["Win32"];
          "Win32_UI_Accessibility" = ["Win32_UI"];
          "Win32_UI_ColorSystem" = ["Win32_UI"];
          "Win32_UI_Controls" = ["Win32_UI"];
          "Win32_UI_Controls_Dialogs" = ["Win32_UI_Controls"];
          "Win32_UI_HiDpi" = ["Win32_UI"];
          "Win32_UI_Input" = ["Win32_UI"];
          "Win32_UI_Input_Ime" = ["Win32_UI_Input"];
          "Win32_UI_Input_KeyboardAndMouse" = ["Win32_UI_Input"];
          "Win32_UI_Input_Pointer" = ["Win32_UI_Input"];
          "Win32_UI_Input_Touch" = ["Win32_UI_Input"];
          "Win32_UI_Input_XboxController" = ["Win32_UI_Input"];
          "Win32_UI_InteractionContext" = ["Win32_UI"];
          "Win32_UI_Magnification" = ["Win32_UI"];
          "Win32_UI_Shell" = ["Win32_UI"];
          "Win32_UI_Shell_Common" = ["Win32_UI_Shell"];
          "Win32_UI_Shell_PropertiesSystem" = ["Win32_UI_Shell"];
          "Win32_UI_TabletPC" = ["Win32_UI"];
          "Win32_UI_TextServices" = ["Win32_UI"];
          "Win32_UI_WindowsAndMessaging" = ["Win32_UI"];
          "Win32_Web" = ["Win32"];
          "Win32_Web_InternetExplorer" = ["Win32_Web"];
        };
        resolvedDefaultFeatures = ["Win32" "Win32_Foundation" "Win32_System" "Win32_System_Time"];
      };
      "wit-bindgen" = rec {
        crateName = "wit-bindgen";
        version = "0.57.1";
        edition = "2024";
        sha256 = "0vjk2jb593ri9k1aq4iqs2si9mrw5q46wxnn78im7hm7hx799gqy";
        libName = "wit_bindgen";
        authors = [
          "Alex Crichton <alex@alexcrichton.com>"
        ];
        features = {
          "async-spawn" = ["async" "dep:futures" "std"];
          "bitflags" = ["dep:bitflags"];
          "default" = ["macros" "realloc" "async" "std" "bitflags" "macro-string"];
          "futures-stream" = ["async" "dep:futures"];
          "inter-task-wakeup" = ["async"];
          "macro-string" = ["wit-bindgen-rust-macro?/macro-string"];
          "macros" = ["dep:wit-bindgen-rust-macro"];
          "rustc-dep-of-std" = ["dep:core" "dep:alloc"];
        };
      };
    };

    #
    # crate2nix/default.nix (excerpt start)
    #

    /*
    Target (platform) data for conditional dependencies.
    This corresponds roughly to what buildRustCrate is setting.
    */
    makeDefaultTarget = platform:
      {
        name = platform.rust.rustcTarget;

        unix = platform.isUnix;
        windows = platform.isWindows;
        fuchsia = true;
        test = false;

        inherit
          (platform.rust.platform)
          arch
          os
          vendor
          ;
        family = platform.rust.platform.target-family;
        env = "gnu";
        endian =
          if platform.parsed.cpu.significantByte.name == "littleEndian"
          then "little"
          else "big";
        pointer_width = toString platform.parsed.cpu.bits;
        debug_assertions = false;
      }
      // extraTargetFlags;

    registryUrl = {
      registries,
      url,
      crate,
      version,
      sha256,
    }: let
      dl = registries.${url}.dl;
      tmpl = [
        "{crate}"
        "{version}"
        "{prefix}"
        "{lowerprefix}"
        "{sha256-checksum}"
      ];
    in
      with lib.strings;
        if lib.lists.any (i: hasInfix "{}" dl) tmpl
        then let
          prefix =
            if builtins.stringLength crate == 1
            then "1"
            else if builtins.stringLength crate == 2
            then "2"
            else "${builtins.substring 0 2 crate}/${builtins.substring 2 (builtins.stringLength crate - 2) crate}";
        in
          builtins.replaceStrings tmpl [
            crate
            version
            prefix
            (lib.strings.toLower prefix)
            sha256
          ]
        else "${dl}/${crate}/${version}/download";

    # Filters common temp files and build files.
    # TODO(pkolloch): Substitute with gitignore filter
    sourceFilter = name: type: let
      baseName = builtins.baseNameOf (builtins.toString name);
    in
      !(
        # Filter out git
        baseName
        == ".gitignore"
        || (type == "directory" && baseName == ".git")
        # Filter out build results
        || (
          type
          == "directory"
          && (
            baseName
            == "target"
            || baseName == "_site"
            || baseName == ".sass-cache"
            || baseName == ".jekyll-metadata"
            || baseName == "build-artifacts"
          )
        )
        # Filter out nix-build result symlinks
        || (type == "symlink" && lib.hasPrefix "result" baseName)
        # Filter out IDE config
        || (type == "directory" && (baseName == ".idea" || baseName == ".vscode"))
        || lib.hasSuffix ".iml" baseName
        # Filter out nix build files
        || baseName == "Cargo.nix"
        # Filter out editor backup / swap files.
        || lib.hasSuffix "~" baseName
        || builtins.match "^\\.sw[a-z]$$" baseName != null
        || builtins.match "^\\..*\\.sw[a-z]$$" baseName != null
        || lib.hasSuffix ".tmp" baseName
        || lib.hasSuffix ".bak" baseName
        || baseName == "tests.nix"
      );

    /*
    Returns a crate which depends on successful test execution
    of crate given as the second argument.

    testCrateFlags: list of flags to pass to the test exectuable
    testInputs: list of packages that should be available during test execution
    */
    crateWithTest = {
      crate,
      testCrate,
      testCrateFlags,
      testInputs,
      testPreRun,
      testPostRun,
    }:
      assert builtins.typeOf testCrateFlags == "list";
      assert builtins.typeOf testInputs == "list";
      assert builtins.typeOf testPreRun == "string";
      assert builtins.typeOf testPostRun == "string"; let
        # override the `crate` so that it will build and execute tests instead of
        # building the actual lib and bin targets We just have to pass `--test`
        # to rustc and it will do the right thing.  We execute the tests and copy
        # their log and the test executables to $out for later inspection.
        test = let
          drv = testCrate.override (_: {
            buildTests = true;
          });
          # If the user hasn't set any pre/post commands, we don't want to
          # insert empty lines. This means that any existing users of crate2nix
          # don't get a spurious rebuild unless they set these explicitly.
          testCommand = pkgs.lib.concatStringsSep "\n" (
            pkgs.lib.filter (s: s != "") [
              testPreRun
              "$f $testCrateFlags 2>&1 | tee -a $out"
              testPostRun
            ]
          );
        in
          pkgs.stdenvNoCC.mkDerivation {
            name = "run-tests-${testCrate.name}";

            inherit (crate) src;

            inherit testCrateFlags;

            buildInputs = testInputs;

            buildPhase = ''
              set -e
              export RUST_BACKTRACE=1

              # build outputs
              testRoot=target/debug
              mkdir -p $testRoot

              # executables of the crate
              # we copy to prevent std::env::current_exe() to resolve to a store location
              for i in ${crate}/bin/*; do
                cp "$i" "$testRoot"
              done
              chmod +w -R .

              # test harness executables are suffixed with a hash, like cargo does
              # this allows to prevent name collision with the main
              # executables of the crate
              hash=$(basename $out)
              for file in ${drv}/tests/*; do
                f=$testRoot/$(basename $file)-$hash
                cp $file $f
                ${testCommand}
              done
            '';
          };
      in
        pkgs.runCommand "${crate.name}-linked"
        {
          inherit (crate) outputs crateName meta;
          passthru =
            (crate.passthru or {})
            // {
              inherit test;
            };
        }
        (
          lib.optionalString (stdenv.buildPlatform.canExecute stdenv.hostPlatform) ''
            echo tested by ${test}
          ''
          + ''
            ${lib.concatMapStringsSep "\n" (output: "ln -s ${crate.${output}} ${"$"}${output}") crate.outputs}
          ''
        );

    # A restricted overridable version of builtRustCratesWithFeatures.
    buildRustCrateWithFeatures = {
      packageId,
      features ? rootFeatures,
      crateOverrides ? defaultCrateOverrides,
      buildRustCrateForPkgsFunc ? null,
      runTests ? false,
      testCrateFlags ? [],
      testInputs ? [],
      # Any command to run immediatelly before a test is executed.
      testPreRun ? "",
      # Any command run immediatelly after a test is executed.
      testPostRun ? "",
    }:
      lib.makeOverridable
      (
        {
          features,
          crateOverrides,
          runTests,
          testCrateFlags,
          testInputs,
          testPreRun,
          testPostRun,
        }: let
          buildRustCrateForPkgsFuncOverriden =
            if buildRustCrateForPkgsFunc != null
            then buildRustCrateForPkgsFunc
            else
              (
                if crateOverrides == pkgs.defaultCrateOverrides
                then buildRustCrateForPkgs
                else
                  pkgs:
                    (buildRustCrateForPkgs pkgs).override {
                      defaultCrateOverrides = crateOverrides;
                    }
              );
          builtRustCrates = builtRustCratesWithFeatures {
            inherit packageId features;
            buildRustCrateForPkgsFunc = buildRustCrateForPkgsFuncOverriden;
            runTests = false;
          };
          builtTestRustCrates = builtRustCratesWithFeatures {
            inherit packageId features;
            buildRustCrateForPkgsFunc = buildRustCrateForPkgsFuncOverriden;
            runTests = true;
          };
          drv = builtRustCrates.crates.${packageId};
          testDrv = builtTestRustCrates.crates.${packageId};
          derivation =
            if runTests
            then
              crateWithTest
              {
                crate = drv;
                testCrate = testDrv;
                inherit
                  testCrateFlags
                  testInputs
                  testPreRun
                  testPostRun
                  ;
              }
            else drv;
        in
          derivation
      )
      {
        inherit
          features
          crateOverrides
          runTests
          testCrateFlags
          testInputs
          testPreRun
          testPostRun
          ;
      };

    /*
    Returns an attr set with packageId mapped to the result of buildRustCrateForPkgsFunc
    for the corresponding crate.
    */
    builtRustCratesWithFeatures = {
      packageId,
      features,
      crateConfigs ? crates,
      buildRustCrateForPkgsFunc,
      runTests,
      makeTarget ? makeDefaultTarget,
    } @ args:
      assert (builtins.isAttrs crateConfigs);
      assert (builtins.isString packageId);
      assert (builtins.isList features);
      assert (builtins.isAttrs (makeTarget stdenv.hostPlatform));
      assert (builtins.isBool runTests); let
        rootPackageId = packageId;
        mergedFeatures = mergePackageFeatures (
          args
          // {
            inherit rootPackageId;
            target =
              makeTarget stdenv.hostPlatform
              // {
                test = runTests;
              };
          }
        );
        # Memoize built packages so that reappearing packages are only built once.
        builtByPackageIdByPkgs = mkBuiltByPackageIdByPkgs pkgs;
        mkBuiltByPackageIdByPkgs = pkgs: let
          self = {
            crates =
              lib.mapAttrs
              (
                packageId: value: buildByPackageIdForPkgsImpl self pkgs packageId
              )
              crateConfigs;
            target = makeTarget pkgs.stdenv.hostPlatform;
            build = mkBuiltByPackageIdByPkgs pkgs.buildPackages;
          };
        in
          self;
        buildByPackageIdForPkgsImpl = self: pkgs: packageId: let
          features = mergedFeatures."${packageId}" or [];
          crateConfig' = crateConfigs."${packageId}";
          crateConfig = builtins.removeAttrs crateConfig' [
            "resolvedDefaultFeatures"
            "devDependencies"
          ];
          devDependencies = lib.optionals (runTests && packageId == rootPackageId) (
            crateConfig'.devDependencies or []
          );
          dependencies = dependencyDerivations {
            inherit features;
            inherit (self) target;
            buildByPackageId = depPackageId:
            # proc_macro crates must be compiled for the build architecture
              if crateConfigs.${depPackageId}.procMacro or false
              then self.build.crates.${depPackageId}
              else self.crates.${depPackageId};
            dependencies = (crateConfig.dependencies or []) ++ devDependencies;
          };
          buildDependencies = dependencyDerivations {
            inherit features;
            inherit (self.build) target;
            buildByPackageId = depPackageId: self.build.crates.${depPackageId};
            dependencies = crateConfig.buildDependencies or [];
          };
          dependenciesWithRenames = let
            buildDeps = filterEnabledDependencies {
              inherit features;
              inherit (self) target;
              dependencies = crateConfig.dependencies or [] ++ devDependencies;
            };
            hostDeps = filterEnabledDependencies {
              inherit features;
              inherit (self.build) target;
              dependencies = crateConfig.buildDependencies or [];
            };
          in
            lib.filter (d: d ? "rename") (hostDeps ++ buildDeps);
          # Crate renames have the form:
          #
          # {
          #    crate_name = [
          #       { version = "1.2.3"; rename = "crate_name01"; }
          #    ];
          #    # ...
          # }
          crateRenames = let
            grouped = lib.groupBy (dependency: dependency.name) dependenciesWithRenames;
            versionAndRename = dep: let
              package = crateConfigs."${dep.packageId}";
            in {
              inherit (dep) rename;
              inherit (package) version;
            };
          in
            lib.mapAttrs (name: builtins.map versionAndRename) grouped;
        in
          buildRustCrateForPkgsFunc pkgs (
            crateConfig
            // {
              src =
                crateConfig.src or (fetchurl rec {
                  name = "${crateConfig.crateName}-${crateConfig.version}.tar.gz";
                  # https://www.pietroalbini.org/blog/downloading-crates-io/
                  # Not rate-limited, CDN URL.
                  url = "https://static.crates.io/crates/${crateConfig.crateName}/${crateConfig.crateName}-${crateConfig.version}.crate";
                  sha256 = assert (lib.assertMsg (crateConfig ? sha256) "Missing sha256 for ${name}");
                    crateConfig.sha256;
                });
              extraRustcOpts =
                lib.lists.optional (targetFeatures != [])
                "-C target-feature=${lib.concatMapStringsSep "," (x: "+${x}") targetFeatures}";
              inherit
                features
                dependencies
                buildDependencies
                crateRenames
                release
                ;
            }
          );
      in
        builtByPackageIdByPkgs;

    # Returns the actual derivations for the given dependencies.
    dependencyDerivations = {
      buildByPackageId,
      features,
      dependencies,
      target,
    }:
      assert (builtins.isList features);
      assert (builtins.isList dependencies);
      assert (builtins.isAttrs target); let
        enabledDependencies = filterEnabledDependencies {
          inherit dependencies features target;
        };
        depDerivation = dependency: buildByPackageId dependency.packageId;
      in
        map depDerivation enabledDependencies;

    /*
    Returns a sanitized version of val with all values substituted that cannot
    be serialized as JSON.
    */
    sanitizeForJson = val:
      if builtins.isAttrs val
      then lib.mapAttrs (n: sanitizeForJson) val
      else if builtins.isList val
      then builtins.map sanitizeForJson val
      else if builtins.isFunction val
      then "function"
      else val;

    # Returns various tools to debug a crate.
    debugCrate = {
      packageId,
      target ? makeDefaultTarget stdenv.hostPlatform,
    }:
      assert (builtins.isString packageId); let
        debug = rec {
          # The built tree as passed to buildRustCrate.
          buildTree = buildRustCrateWithFeatures {
            buildRustCrateForPkgsFunc = _: lib.id;
            inherit packageId;
          };
          sanitizedBuildTree = sanitizeForJson buildTree;
          dependencyTree = sanitizeForJson (buildRustCrateWithFeatures {
            buildRustCrateForPkgsFunc = _: crate: {
              "01_crateName" = crate.crateName or false;
              "02_features" = crate.features or [];
              "03_dependencies" = crate.dependencies or [];
            };
            inherit packageId;
          });
          mergedPackageFeatures = mergePackageFeatures {
            features = rootFeatures;
            inherit packageId target;
          };
          diffedDefaultPackageFeatures = diffDefaultPackageFeatures {
            inherit packageId target;
          };
        };
      in {
        internal = debug;
      };

    /*
    Returns differences between cargo default features and crate2nix default
    features.

    This is useful for verifying the feature resolution in crate2nix.
    */
    diffDefaultPackageFeatures = {
      crateConfigs ? crates,
      packageId,
      target,
    }:
      assert (builtins.isAttrs crateConfigs); let
        prefixValues = prefix: lib.mapAttrs (n: v: {"${prefix}" = v;});
        mergedFeatures = prefixValues "crate2nix" (mergePackageFeatures {
          inherit crateConfigs packageId target;
          features = ["default"];
        });
        configs = prefixValues "cargo" crateConfigs;
        combined = lib.foldAttrs (a: b: a // b) {} [
          mergedFeatures
          configs
        ];
        onlyInCargo = builtins.attrNames (
          lib.filterAttrs (n: v: !(v ? "crate2nix") && (v ? "cargo")) combined
        );
        onlyInCrate2Nix = builtins.attrNames (
          lib.filterAttrs (n: v: (v ? "crate2nix") && !(v ? "cargo")) combined
        );
        differentFeatures =
          lib.filterAttrs
          (
            n: v:
              (v ? "crate2nix")
              && (v ? "cargo")
              && (v.crate2nix.features or []) != (v."cargo".resolved_default_features or [])
          )
          combined;
      in
        builtins.toJSON {
          inherit onlyInCargo onlyInCrate2Nix differentFeatures;
        };

    /*
    Returns an attrset mapping packageId to the list of enabled features.

    If multiple paths to a dependency enable different features, the
    corresponding feature sets are merged. Features in rust are additive.
    */
    mergePackageFeatures = {
      crateConfigs ? crates,
      packageId,
      rootPackageId ? packageId,
      features ? rootFeatures,
      dependencyPath ? [crates.${packageId}.crateName],
      featuresByPackageId ? {},
      target,
      # Adds devDependencies to the crate with rootPackageId.
      runTests ? false,
      ...
    } @ args:
      assert (builtins.isAttrs crateConfigs);
      assert (builtins.isString packageId);
      assert (builtins.isString rootPackageId);
      assert (builtins.isList features);
      assert (builtins.isList dependencyPath);
      assert (builtins.isAttrs featuresByPackageId);
      assert (builtins.isAttrs target);
      assert (builtins.isBool runTests); let
        crateConfig = crateConfigs."${packageId}" or (builtins.throw "Package not found: ${packageId}");
        expandedFeatures = expandFeatures (crateConfig.features or {}) features;
        enabledFeatures = enableFeatures (crateConfig.dependencies or []) expandedFeatures;
        depWithResolvedFeatures = dependency: let
          inherit (dependency) packageId;
          features = dependencyFeatures enabledFeatures dependency;
        in {
          inherit packageId features;
        };
        resolveDependencies = cache: path: dependencies:
          assert (builtins.isAttrs cache);
          assert (builtins.isList dependencies); let
            enabledDependencies = filterEnabledDependencies {
              inherit dependencies target;
              features = enabledFeatures;
            };
            directDependencies = map depWithResolvedFeatures enabledDependencies;
            foldOverCache = op: lib.foldl op cache directDependencies;
          in
            foldOverCache (
              cache: {
                packageId,
                features,
              }: let
                cacheFeatures = cache.${packageId} or [];
                combinedFeatures = sortedUnique (cacheFeatures ++ features);
              in
                if cache ? ${packageId} && cache.${packageId} == combinedFeatures
                then cache
                else
                  mergePackageFeatures {
                    features = combinedFeatures;
                    featuresByPackageId = cache;
                    inherit
                      crateConfigs
                      packageId
                      target
                      runTests
                      rootPackageId
                      ;
                  }
            );
        cacheWithSelf = let
          cacheFeatures = featuresByPackageId.${packageId} or [];
          combinedFeatures = sortedUnique (cacheFeatures ++ enabledFeatures);
        in
          featuresByPackageId
          // {
            "${packageId}" = combinedFeatures;
          };
        cacheWithDependencies = resolveDependencies cacheWithSelf "dep" (
          crateConfig.dependencies or []
          ++ lib.optionals (runTests && packageId == rootPackageId) (crateConfig.devDependencies or [])
        );
        cacheWithAll = resolveDependencies cacheWithDependencies "build" (
          crateConfig.buildDependencies or []
        );
      in
        cacheWithAll;

    # Returns the enabled dependencies given the enabled features.
    filterEnabledDependencies = {
      dependencies,
      features,
      target,
    }:
      assert (builtins.isList dependencies);
      assert (builtins.isList features);
      assert (builtins.isAttrs target);
        lib.filter
        (
          dep: let
            targetFunc = dep.target or (features: true);
          in
            targetFunc {inherit features target;}
            && (!(dep.optional or false) || builtins.any (doesFeatureEnableDependency dep) features)
        )
        dependencies;

    # Returns whether the given feature should enable the given dependency.
    doesFeatureEnableDependency = dependency: feature: let
      name = dependency.rename or dependency.name;
      prefix = "${name}/";
      len = builtins.stringLength prefix;
      startsWithPrefix = builtins.substring 0 len feature == prefix;
    in
      feature == name || feature == "dep:" + name || startsWithPrefix;

    /*
    Returns the expanded features for the given inputFeatures by applying the
    rules in featureMap.

    featureMap is an attribute set which maps feature names to lists of further
    feature names to enable in case this feature is selected.
    */
    expandFeatures = featureMap: inputFeatures:
      assert (builtins.isAttrs featureMap);
      assert (builtins.isList inputFeatures); let
        expandFeaturesNoCycle = oldSeen: inputFeatures:
          if inputFeatures != []
          then let
            # The feature we're currently expanding.
            feature = builtins.head inputFeatures;
            # All the features we've seen/expanded so far, including the one
            # we're currently processing.
            seen =
              oldSeen
              // {
                ${feature} = 1;
              };
            # Expand the feature but be careful to not re-introduce a feature
            # that we've already seen: this can easily cause a cycle, see issue
            # #209.
            enables = builtins.filter (f: !(seen ? "${f}")) (featureMap."${feature}" or []);
          in
            [feature] ++ (expandFeaturesNoCycle seen (builtins.tail inputFeatures ++ enables))
          # No more features left, nothing to expand to.
          else [];
        outFeatures = expandFeaturesNoCycle {} inputFeatures;
      in
        sortedUnique outFeatures;

    /*
    This function adds optional dependencies as features if they are enabled
    indirectly by dependency features. This function mimics Cargo's behavior
    described in a note at:
    https://doc.rust-lang.org/nightly/cargo/reference/features.html#dependency-features
    */
    enableFeatures = dependencies: features:
      assert (builtins.isList features);
      assert (builtins.isList dependencies); let
        additionalFeatures =
          lib.concatMap
          (
            dependency:
              assert (builtins.isAttrs dependency); let
                enabled = builtins.any (doesFeatureEnableDependency dependency) features;
              in
                if (dependency.optional or false) && enabled
                then [(dependency.rename or dependency.name)]
                else []
          )
          dependencies;
      in
        sortedUnique (features ++ additionalFeatures);

    /*
    Returns the actual features for the given dependency.

    features: The features of the crate that refers this dependency.
    */
    dependencyFeatures = features: dependency:
      assert (builtins.isList features);
      assert (builtins.isAttrs dependency); let
        defaultOrNil =
          if dependency.usesDefaultFeatures or true
          then ["default"]
          else [];
        explicitFeatures = dependency.features or [];
        additionalDependencyFeatures = let
          name = dependency.rename or dependency.name;
          stripPrefixMatch = prefix: s:
            if lib.hasPrefix prefix s
            then lib.removePrefix prefix s
            else null;
          extractFeature = feature:
            lib.findFirst (f: f != null) null (
              map (prefix: stripPrefixMatch prefix feature) [
                (name + "/")
                (name + "?/")
              ]
            );
          dependencyFeatures = lib.filter (f: f != null) (map extractFeature features);
        in
          dependencyFeatures;
      in
        defaultOrNil ++ explicitFeatures ++ additionalDependencyFeatures;

    # Sorts and removes duplicates from a list of strings.
    sortedUnique = features:
      assert (builtins.isList features);
      assert (builtins.all builtins.isString features); let
        outFeaturesSet = lib.foldl (set: feature: set // {"${feature}" = 1;}) {} features;
        outFeaturesUnique = builtins.attrNames outFeaturesSet;
      in
        builtins.sort (a: b: a < b) outFeaturesUnique;

    deprecationWarning = message: value:
      if strictDeprecation
      then builtins.throw "strictDeprecation enabled, aborting: ${message}"
      else builtins.trace message value;

    #
    # crate2nix/default.nix (excerpt end)
    #
  };
}
