return (function()
  vim.keymap.set("n", "<leader>d", '"+d', { })
  vim.keymap.set("n", "<leader>y", '"+y', { })
  vim.keymap.set("n", "<leader>p", '"+p', { })
  vim.keymap.set("n", "<leader>D", '"*d', { })
  vim.keymap.set("n", "<leader>Y", '"*y', { })
  vim.keymap.set("n", "<leader>P", '"*p', { })
  vim.keymap.set("v", "<C-v>", '"+p', { })
  vim.keymap.set("v", "<C-c>", '"+y', { })
  vim.keymap.set("v", "<C-x>", '"+d', { })
  return vim.keymap.set("i", "<C-v>", '<esc>"+pi', { })
end)()
