name: 'Format Check'
description: 'Run treefmt format check'
runs:
  using: 'composite'
  steps:
    - name: Install devenv
      shell: bash
      run: nix profile install nixpkgs#devenv
    - name: Run lint
      shell: bash
      run: ./bin/ci/lint
