name: 'Setup Nix and Cachix'
description: 'Install Nix and configure Cachix'
runs:
  using: 'composite'
  steps:
    - name: Install Nix
      uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Install Cachix
      uses: cachix/cachix-action@v14
      with:
        name: devenv
    - name: Install devenv
      shell: bash
      run: nix profile install nixpkgs#devenv
