name: Flake Check

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - auto_merge_enabled

jobs:
  flake-check:
    name: Flake Check
    runs-on: ubuntu-22.04
    steps:
      - name: Enable Pull Request Automerge
        run: gh pr merge --merge --auto "1"
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/flake-checker-action@v4
      # - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix flake check
