name: Flake Check

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - auto_merge_enabled

jobs:
  flake-check:
    name: Flake Check
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Enable Pull Request Automerge
        run: gh pr merge --rebase --delete-branch --auto "${GITHUB_REF##*/}"
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Install Flake Check
        uses: DeterminateSystems/flake-checker-action@v4
      # - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Run Flake Check
        run: nix flake check
