name: Flake Check

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - auto_merge_enabled

jobs:
  flake-check:
    name: Flake Check
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - name: Enable Pull Request Automerge
        run: gh pr merge --squash --delete-branch --auto "${{steps.extract_branch.outputs.branch}}"
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Install Flake Check
        uses: DeterminateSystems/flake-checker-action@v4
      # - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Run Flake Check
        run: nix flake check
