name: Nix Flake actions
# yamllint disable-line rule:truthy
on:
  pull_request:
  push:
    branches:
      - master
      - main
jobs:
  devenv:
    runs-on: ubuntu-latest
    steps:
      - name: Install > Checkout
        uses: actions/checkout@v4
      - name: Install > Nix
        uses: cachix/install-nix-action@v26
      - name: Install > Cachix
        uses: cachix/cachix-action@v14
        with:
          name: devenv
      - name: Install > DevEnv
        run: nix profile install nixpkgs#devenv
      - name: DevEnv > Lint
        run: devenv lint
      - name: DevEnv > Test
        run: devenv test
