name: Unit Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  # flake-check:
  #   name: Flake Check
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     # - name: Extract branch name
  #     #   shell: bash
  #     #   run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
  #     #   id: extract_branch
  #     # - name: Enable Pull Request Automerge
  #     #   run: gh pr merge --squash --delete-branch --auto "${{steps.extract_branch.outputs.branch}}"
  #     #   env:
  #     #     GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
  #     - name: Install Nix
  #       uses: DeterminateSystems/nix-installer-action@main
  #     - name: Install Magic Nix Cache
  #       uses: DeterminateSystems/magic-nix-cache-action@main
  #     - name: Install Flake Check
  #       uses: DeterminateSystems/flake-checker-action@v4
  #     - name: Run Flake Check
  #       run: nix flake check
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Install Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Unit Test
        run: nix run nixpkgs#nix-unit --flake .#tests
  # build-nixos:
  #   name: Build NixOS
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - name: Install Nix
  #       uses: DeterminateSystems/nix-installer-action@main
  #     - name: Install Magic Nix Cache
  #       uses: DeterminateSystems/magic-nix-cache-action@main
  #     - name: Unit Test
  #       run: bin/update-nixos langhus tom
